### ISSUE TITLE
getHosts() in FiberSensor is not threadsafe

### ISSUE THREAD

**Issue by WinkerDu** [Intel-bigdata/OAP#1023]
![NPE_getHosts](https://user-images.githubusercontent.com/11454734/54656724-bf6aaa80-4b01-11e9-8a31-eb121ee9ef54.png)

getHosts() could raise NPE in concurrency scenarios, 
`val hosts = if (fileToHosts.containsKey(filePath)) {
      fileToHosts.get(filePath)
    } else {
      new ArrayBuffer[HostFiberCache](0)
    }` 
should be replaced with 'computeIfAbsent' implement

**Comment by LuciferYang** [comment]
Good cache ~ we need fix this bug in current version, @WinkerDu Can you help fix it?

**Comment by WinkerDu** [comment]
@LuciferYang  OK, happy to fix it

**Comment by LuciferYang** [comment]
done
