### ISSUE TITLE
OAP Index meta version  compatibility bugs

### ISSUE THREAD

**Issue by lidinghao** [Intel-bigdata/OAP#1048]
In DataSourceMeta, we use a Set(versionSet) to record all meta versions,  current code as follows:
DataSourceMeta.scala:300  
val versionSet = Set(Version(1, 0, 1), Version(1, 0, 1))

there is a typo/bug in the above code， which doesn't contain Version(1, 0, 0).

the correct code should  be :
val versionSet = Set(Version(1, 0, 0), Version(1, 0, 1))

**Comment by LuciferYang** [comment]
#1049 fix this
