### ISSUE TITLE
Out of Memory issue when build index on large size file

### ISSUE THREAD

**Issue by shaowenzh** [Intel-bigdata/OAP#1052]
Got out of memory exception reported when build index on 500mb size file. 
```
  def addOapKey(key: Key): Unit = {
    if (key.anyNull || stats.isEmpty) {
      // stats info does not collect null keys
      return
    }
    content.append(key)
    stats.foreach(_.addOapKey(key))
  }
```
In StatisticsManager, this `content ` load all the file data and used to calculate PartByValueStatistic and SampleBasedStatistic. This will consume lots of memory when the file is very large.

**Comment by LuciferYang** [comment]
How many columns and rows are there in this file?

**Comment by shaowenzh** [comment]
@LuciferYang According to the reporter, they tested on trying to set up index on around 500mb TPC-DS parquet file. From my local test, a 340mb parquet file around 7200000 rows will got a very heavy GC.
