### ISSUE TITLE
Task Failure when running 3TB-scale TPC-DS on ORC Binary Vmemcache 

### ISSUE THREAD

**Issue by HongW2019** [Intel-bigdata/OAP#1168]
When running 3TB-scale TPC-DS, task failed due to  "org.apache.spark.sql.execution.datasources.OapException: cache guardian use too much memory". According to OAP User Guide for ORC Binary Vmemcache Cache,  the configurations in spark-defaults.conf are listed below and the cluster consists of one node(cores:96, memory:320G, DCPMM: 2*488G) 
_spark.sql.oap.fiberCache.memory.manager tmp 
spark.oap.cache.strategy  vmem 
spark.sql.oap.orc.binary.cache.enable true 
spark.memory.offHeap.enabled false 
spark.executor.instances 2 
spark.executor.cores 45 
spark.executor.memory 140g 
spark.executor.memoryOverhead 2731 
spark.driver.memory 10g 
spark.sql.oap.cache.guardian.memory.size  20g 
spark.sql.oap.fiberCache.persistent.memory.initial.size 463g_

Then we tried to increase _spark.sql.oap.cache.guardian.free.thread.nums_ _spark.sql.oap.cache.guardian.memory.size_  to a larger number, the configurations are listed below:
_spark.executor.memory 110g 
spark.executor.memoryOverhead 40g 
spark.driver.memory 10g 
spark.sql.oap.cache.guardian.memory.size  100g 
spark.sql.oap.cache.guardian.free.thread.nums  10
spark.sql.oap.fiberCache.persistent.memory.initial.size 463g_

But task failed:
![image](https://user-images.githubusercontent.com/30172512/77490927-4e2da800-6e77-11ea-8168-cc2477179dd7.png)

So we need figure out the proper way to config then adding to OAP User Guide, or is there something to fix on ORC Binary Vmemcache?

**Comment by HongW2019** [comment]
Please help to figure out the issue. Thx. @jikunshang  @linnashuang  @yeyuqiang

**Comment by jikunshang** [comment]
@HongW2019  It's right to increase these two configs. But spark.executor.memory + spark.sql.oap.cache.guardian.memory.size should be no more than half of machine physical memory. And Yarn will have some mechanism to detect executor memory usage and  kill executors, that's why case 2 failed.  It's suggested that set spark.sql.oap.cache.guardian.memory.size to 40g. This config spark.sql.oap.cache.guardian.memory.size depends on test dataset scale.

**Comment by HongW2019** [comment]
@jikunshang Thanks for your advice. After limited spark.executor.memory + spark.sql.oap.cache.guardian.memory.size < 1/2 physical memory, Task still failed due to "org.apache.spark.sql.execution.datasources.OapException: cache guardian use too much memory"
Below is configs:
spark.executor.memory 90g 
spark.executor.memoryOverhead 40g 
spark.sql.oap.cache.guardian.memory.size  40g 
spark.sql.oap.cache.guardian.free.thread.nums  10
spark.sql.oap.fiberCache.persistent.memory.initial.size 463g

Even increasing to 60g, task still failed.

**Comment by zhixingheyi-tian** [comment]
#1170  resolved this issue
