### ISSUE TITLE
PR title includes module names

### ISSUE THREAD

**Issue by gczsjdy** [Intel-bigdata/OAP#1173]
Since OAP currently contains many modules that work separately, should we create a new rule for PRs and issues? 
- A PR/issue doesn't need [module] name in the title
- A PR/issue for a specific module needs to include the module name in the title, like https://github.com/apache/spark/pulls

**Comment by carsonwang** [comment]
Good idea. cc @jerrychenhf

**Comment by winningsix** [comment]
+1

**Comment by gczsjdy** [comment]
Close this, new PRs and issues are following this rule.
