### ISSUE TITLE
Vmemcache strategy met ERROR when setting the compression codec to SNAPPY

### ISSUE THREAD

**Issue by HongW2019** [Intel-bigdata/OAP#1186]
Vmemcache strategy met ERROR when running Daily test, which is, setting the compression codec to SNAPPY when writing data fiber cache will cause lots of tasks failed and then queries failed.
You can locate the issue with spark-shell quickly after:
	1. Generating 200G Parquet tpcds store_sales table with index.
        ```
scala>spark.sql( s"CREATE OINDEX  store_sales_ss_item_sk1_index ON store_sales (ss_item_sk1) USING BITMAP")
	```
	2. Adding the following configs to spark-defaults.conf:
```
	spark.executor.memoryOverhead                            20g
        spark.sql.oap.cache.guardian.memory.size                 20g
        spark.sql.oap.cache.guardian.free.thread.nums            10
        spark.sql.oap.parquet.data.cache.enable                  true
        spark.sql.oap.parquet.index.enable                       false
        spark.sql.oap.fiberCache.memory.manager                  tmp
        spark.oap.cache.strategy                                 vmem
        spark.sql.oap.data.fiber.cache.compress.enable           true
        spark.sql.oap.data.fiber.cache.compression.codec         SNAPPY
```
       3. Run the following queries in spark-shell 
	scala>spark.sql(s"use parquet200")
	scala>spark.sql("SELECT * FROM store_sales WHERE ss_item_sk1 in ('1, 2, 3, 4, 5, 6, 7, 8, 9, 10')").foreach{ _ => }; spark.sql("SELECT * FROM store_sales WHERE ss_item_sk1 in ('1, 2, 3, 4, 5, 6, 7, 8, 9, 10')").foreach{ _ => };spark.sql("SELECT * FROM store_sales WHERE ss_item_sk1 in ('1, 2, 3, 4, 5, 6, 7, 8, 9, 10')").foreach{ _ => }; spark.sql("SELECT * FROM store_sales WHERE ss_item_sk1 in ('1, 2, 3, 4, 5')").foreach{ _ => };spark.sql("SELECT * FROM store_sales WHERE ss_item_sk1 in ('1, 2, 3, 4, 5')").foreach{ _ => }

**Comment by winningsix** [comment]
Thanks @HongW2019 for reporting this. Could you paste the error msg here?

**Comment by HongW2019** [comment]
![image](https://user-images.githubusercontent.com/30172512/78769384-e2dbee00-79bf-11ea-89e7-64899d0029cd.png)
@winningsix  For detailed error msg, have been in sync with @	jikunshang

**Comment by winningsix** [comment]
@HongW2019 Already sync'd. Thanks for reporting this issue!

**Comment by winningsix** [comment]
@zhixingheyi-tian The root cause is identified. But I am wondering when will FiberCache compression used. It seems performance will be impact quite a lot due to decompression.

**Comment by zhixingheyi-tian** [comment]
@winningsix 
Hi,  this is a basic feature for OAP 0.6/0.7.

Before, it was mainly to save memory space, which inevitably brought performance loss. It may be removed in a future version.

Thanks

**Comment by winningsix** [comment]
I would suggest to make it an unsupported feature for Vmemcache considering its priority.
