### ISSUE TITLE
[oap-native-sql]arrow lib dir is hardcoded in codegen

### ISSUE THREAD

**Issue by zhouyuan** [Intel-bigdata/OAP#1373]
https://github.com/Intel-bigdata/OAP/blob/branch-nativesql-spark-3.0.0/oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_common.cc#L222

`lib64` may not be correct, some release use `lib`

**Comment by xuechendi** [comment]
@zhouyuan ,  This is a configurable variable I think, and we can also add a config in scala ColumnarPluginConfig as batch_size and passdown here.

**Comment by zhouyuan** [comment]
@xuechendi no, the "lib64" is hard coded right now
https://github.com/Intel-bigdata/OAP/blob/branch-nativesql-spark-3.0.0/oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_common.cc#L237

**Comment by zhouyuan** [comment]
#1395
