### ISSUE TITLE
[oap-native-sql] support ExistenceJoin 

### ISSUE THREAD

**Issue by zhouyuan** [Intel-bigdata/OAP#1458]

**Comment by rui-mo** [comment]
ExistenceJoin uses one boolean col to mark if distinct left key exists. Usually the buildType is BuildRight, and output cols are "stream cols :+ exists col". For example:
left_schema is List(c_customer_sk#202, c_current_cdemo_sk#204, c_current_addr_sk#206), right_schema is List(ws_bill_customer_sk#734), 
leftKeys is List(c_customer_sk#202), rightKeys is List(ws_bill_customer_sk#734), 
resultSchema is StructType(StructField(c_customer_sk,IntegerType,true), StructField(c_current_cdemo_sk,IntegerType,true), StructField(c_current_addr_sk,IntegerType,true), StructField(exists,BooleanType,false)), 
joinType is ExistenceJoin(exists#1110), buildSide is BuildRight, condition is None

**Comment by zhouyuan** [comment]
fixed in #1400
