### ISSUE TITLE
[oap-shuffle][RPMem shuffle] Can not successfully run TPC-DS with RPMem shuffle in the version of 0.9.0.

### ISSUE THREAD

**Issue by haojinIntel** [Intel-bigdata/OAP#1460]
We try to run TPC-DS with RPMem shuffle plugin and catch the error message like:
![image](https://user-images.githubusercontent.com/44394375/87110394-87a8e880-c299-11ea-9945-bbbe50e5b7ef.png)
@Eugene-Mark Please help to fix this bug.

**Comment by Jian-Zhang** [comment]
@haojinIntel This should be fixed with https://github.com/Intel-bigdata/OAP/pull/1465, can you help to verify? Thanks

**Comment by haojinIntel** [comment]
@Jian-Zhang @Eugene-Mark This issue has been fixed and I will close it.
