### ISSUE TITLE
[SQL Index and Data Source Cache] Remove ORC `spark.sql.orc.copyBatchToSpark` related codes to support Spark-3.0.0

### ISSUE THREAD

**Issue by HongW2019** [Intel-bigdata/OAP#1464]
Spark-3.0.0[SPARK-26584] has removed the configuration `spark.sql.orc.copyBatchToSpark` and related ORC codes including tests and benchmarks. So OAP SQL Index and Data Source Cache needs made corresponding change to support Spark-3.0.0.

**Comment by zhixingheyi-tian** [comment]
@HongW2019 , write the  write link here for this issue
