### ISSUE TITLE
[SQL Index and Data Source Cache] [oap-spark] Conflicts between RDD Cache and Data Source Cache.

### ISSUE THREAD

**Issue by haojinIntel** [Intel-bigdata/OAP#1466]
When I try to add all features of OAP-0.8.1 in spark-defaults.conf and test RDD cache, the kmeans worklload faild thanks to the conflict between oap-cache-0.8.1-with-spark-2.4.4.jar and oap-spark-0.8.1-with-spark-2.4.4.jar. If I remove the config of oap-cache-0.8.1-with-spark-2.4.4.jar, the test run successfully.
![image](https://user-images.githubusercontent.com/44394375/87278485-255d1b80-c517-11ea-91f3-f564371738fa.png)

@yeyuqiang @winningsix  Please fix the conflict so that the features about PMEM can work together.

**Comment by zhixingheyi-tian** [comment]
@haojinIntel 
Would you please paste the  "error" Infos

**Comment by haojinIntel** [comment]
Cannot start-up executors.
![image](https://user-images.githubusercontent.com/44394375/87281648-05812400-c526-11ea-83ad-cfad95cee82b.png)
