### ISSUE TITLE
[oap-native-sql] clean up metrics name in CoalesceBatches

### ISSUE THREAD

**Issue by zhouyuan** [Intel-bigdata/OAP#1477]
The total is repeated in the metrics:

concat batch time **total total** (min, med, max (stageId: taskId))
88 ms (0 ms, 0 ms, 24 ms (stage 1.0: task 1187))
number of output batches: 4
number of input rows: 4,608
number of input batches: 4,608
collect batch time **total total** (min, med, max (stageId: taskId))
1.4 s (0 ms, 0 ms, 356 ms (stage 1.0: task 1159))
avg coalesced batch num rows (min, med, max (stageId: taskId)):
(1,152, 1,152, 1,152 (stage 1.0: task 1159))

https://github.com/Intel-bigdata/OAP/blob/4e0c2e44b1ee5160dfed0ba11e90780b8d27a57c/oap-native-sql/core/src/main/scala/com/intel/oap/execution/CoalesceBatchesExec.scala#L48-L49

**Comment by rongma1997** [comment]
Thanks! Will do a quick fix.

**Comment by zhouyuan** [comment]
fixed in #1497
