### ISSUE TITLE
[rpmem-shuffle] The spark version of rpmem shuffle is in preview version for travis CI process

### ISSUE THREAD

**Issue by Eugene-Mark** [Intel-bigdata/OAP#1492]
The spark-3.0.0-bin-hadoop2.7.tgz should be downloaded for CI process instead of spark-3.0.0-preview2-bin-hadoop2.7.tgz.

**Comment by zhixingheyi-tian** [comment]
Hi Eugene， Does this  issue be solved ?

**Comment by Eugene-Mark** [comment]
@zhixingheyi-tian Yes, it has been fixed by PR https://github.com/Intel-bigdata/OAP/pull/1494. I will close the issue.
