### ISSUE TITLE
[oap-native-sql] disable codegen for columnar operator

### ISSUE THREAD

**Issue by zhouyuan** [Intel-bigdata/OAP#1527]
should disable spark level codegen for columnar operator
`verride def supportCodegen: Boolean = false`

**Comment by xuechendi** [comment]
@zhouyuan , I think we have added this line in all operators who is derive from CodegenSupport, remaining operators are all not derive from CodegenSupport class, so we don't need to override supportCodegen there

**Comment by zhouyuan** [comment]
@xuechendi I found there are still several operators didnt disable this. if it's not necessary then let's close this issue
