### ISSUE TITLE
[oap-native-sql] TreeNode children not replaced by columnar operators

### ISSUE THREAD

**Issue by zhztheplayer** [Intel-bigdata/OAP#1541]
`TreeNode.withNewChildren(...)` depends on children's implementation of `fastEquals`[1]. That said replacement happens only if new child is **not equal to** old child. However e.g. `ColumnarHashAggregateExec` will be equal to regular `HashAggregateExec` if both have same fields which means the replacement is not always reliable as we expect. Which means we can probably get a `HashAggregateExec` rather than `ColumnarHashAggregateExec` in physical plan even if the columnar rules has been processed on the aggregation node. 

@zhouyuan @xuechendi Have you been experiencing such a problem as I suppose the issue should happen regularly in many cases even a simple `select a, sum(b) from t group by a limit 10`.

[1] https://github.com/Intel-bigdata/spark/blob/3fdfce3120f307147244e5eaf46d61419a723d50/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/trees/TreeNode.scala#L253

**Comment by xuechendi** [comment]
@zhztheplayer , so according to FastEquals inside withNewChildren, the scenario we would see is columnarHashAggregateExec won't replace original Exec, right?
Looks like we didn't met issues like this, but I think maybe we should override fastEquals to ensure.

**Comment by zhztheplayer** [comment]
> so according to FastEquals inside withNewChildren, the scenario we would see is columnarHashAggregateExec won't replace original Exec, right?

Yes, this is what happened in my test. If the issue can be confirmed by both of us then we can prepare for a patch.
