### ISSUE TITLE
[SQL Index and Data Source Cache] The performance of Plasma is lower than vmemcache when using Column Vector Cache

### ISSUE THREAD

**Issue by haojinIntel** [Intel-bigdata/OAP#1557]
I just use automatically testing infrastructure to collect the performance data of OAP Data Source Cache for the first round. The configuration of cluster is like:
![image](https://user-images.githubusercontent.com/44394375/89137986-93bc5900-d56c-11ea-9c9e-e2491123d770.png)
The data scale is 3TB and the capacity of PMEM is enough for cache. All results is showed below:：
![image](https://user-images.githubusercontent.com/44394375/89138032-c2d2ca80-d56c-11ea-9720-9d1389d32d46.png)
The performance of Plasma is 27% less than vmemcache when using Colomn Vector cache and the capacity of PMEM is enough.

**Comment by jikunshang** [comment]
We have re-run this case with numa-patched spark, plasma get better performance than guava and vmemcache. So it's strongly suggested that use numa-patched spark. I will update related document.
![image](https://user-images.githubusercontent.com/50897707/89548364-838cce00-d839-11ea-858c-32150e218eaf.png)
