### ISSUE TITLE
[SQL Index and Data Source Cache] The web UI cannot show cache size when using Plasma and q68.sql will be suspended to wait for cache free. 

### ISSUE THREAD

**Issue by haojinIntel** [Intel-bigdata/OAP#1579]
I run 9 IO-intensive queries of TPCDS for 3 rounds and use Plasma Service for data source cache. The data scale is 3TB and PEME is enough for cache. There are two issues were found:
1. When running queries for the 2nd round, q68.sql will be suspended and wait for cache free which causes the test fail:
![image](https://user-images.githubusercontent.com/44394375/89600457-b7491180-d894-11ea-93d7-95fe8d8e2efb.png)
2. The web UI cannot accuratly display the cache size:
![image](https://user-images.githubusercontent.com/44394375/89600566-ecedfa80-d894-11ea-9bf7-b85588ce5f07.png)

**Comment by zhixingheyi-tian** [comment]
cc @jikunshang

**Comment by jikunshang** [comment]
The first issue can be resolved by increasing `spark.sql.oap.dcpmm.free.wait.threshold` configuration, it's maximum cache size one executor could get.
