### ISSUE TITLE
[oap-native-sql] Hash Collision in multiple keys scenario

### ISSUE THREAD

**Issue by xuechendi** [Intel-bigdata/OAP#1580]
We noticed hash collision in tpch Q16 using current way of generating gandiva hashcode
(base) [root@sr602 tpch_test]# grep -r "2131584127" /hadoop/logs/userlogs/application_1596726092887_0025/
/hadoop/logs/userlogs/application_1596726092887_0025/container_1596726092887_0025_01_000018/stdout:[2131584127]:Brand#34, LARGE PLATED COPPER, 9, 189920
/hadoop/logs/userlogs/application_1596726092887_0025/container_1596726092887_0025_01_000018/stdout:[2131584127]:Brand#12, ECONOMY ANODIZED STEEL, 19, 796564
/hadoop/logs/userlogs/application_1596726092887_0025/container_1596726092887_0025_01_000013/stdout:[2131584127]:Brand#34, LARGE PLATED COPPER, 9, 189920

**Comment by xuechendi** [comment]
@zhouyuan , fired issue here, we need to come up a better way to ensure hash performance and handle hash collision well
Current we used  (hash32 (hash32(hash32) *10)* 10)

**Comment by zhouyuan** [comment]
@xuechendi thanks for the look, i'll check if we could fix this easily as this also occurs in 0.9

**Comment by zhouyuan** [comment]
This should be fixed in master now
