### ISSUE TITLE
[oap-native-sql] Cannot run TPC-H for several rounds.

### ISSUE THREAD

**Issue by haojinIntel** [Intel-bigdata/OAP#1620]
For stability test, we use 1.5TB dataset and run all TPC-H queries for 65 rounds which can last for 3 days. The test will be suspended in the 3rd round  with unknown issues. The resource of cluster is enough and the cluster is healthy. While no tasks will be actived.

**Comment by zhixingheyi-tian** [comment]
cc  @zhouyuan

**Comment by zhouyuan** [comment]
@zhixingheyi-tian hao has some new findings, the issue seems on spark-shell

**Comment by zhouyuan** [comment]
the issue seems related with spark-shell. thrift-server is supported on master now. @haojinIntel
