### ISSUE TITLE
[SQL Data Source Cache] The task will be suspended when using plasma cache and starting 2 executors per worker.

### ISSUE THREAD

**Issue by haojinIntel** [Intel-bigdata/OAP#1640]
I run 9 IO-intensive queries of TPCDS  1200 rounds for stress test and use Plasma Service for data source cache. The data scale is 3TB and PEME is enough for cache. We found that the test will be suspend in high frequency if the number of executor is 2 on per worker.

**Comment by haojinIntel** [comment]
@jikunshang Please follow the issue.

**Comment by jikunshang** [comment]
#2004

**Comment by zhixingheyi-tian** [comment]
CC @haojinIntel 
Would you please add some logs or snapshot for 0.8 branch and 1.0 branch  hang issues?

**Comment by haojinIntel** [comment]
We can see thread dump for Spark UI and get message like below:
![image](https://user-images.githubusercontent.com/44394375/101444751-1ca03280-395b-11eb-92a8-93d08b172183.png)
The program will be  pending on this code:
![image](https://user-images.githubusercontent.com/44394375/101445177-fa5ae480-395b-11eb-9d42-938f56f4f128.png)
We can avoid this issue to improve the value of spark.sql.oap.dcpmm.free.wait.threshold or remove this logical judgment for plasma.
