### ISSUE TITLE
[OAP-CACHE] should init fs with table path when drop index.

### ISSUE THREAD

**Issue by ivoson** [Intel-bigdata/OAP#1677]
When drop index [indexPlans](https://github.com/Intel-bigdata/OAP/blob/master/oap-cache/oap/src/main/scala/org/apache/spark/sql/execution/datasources/oap/index/indexPlans.scala#L245), we get fs with path.getFileSystem(conf) instead of FileSystem.get(conf) which init fs with fs.default. If the table location is not on defaut fs, we will fail droping index file.

**Comment by LuciferYang** [comment]
reolved
