### ISSUE TITLE
[oap-shuffle][RPMem shuffle] Class PmemBuffer load native library only support in the specified path

### ISSUE THREAD

**Issue by yao531441** [Intel-bigdata/OAP#1741]
In class PmemBuffer, we will load native library like blow:
```
static {
        System.load("/usr/local/lib/libjnipmdk.so");
}
```
This is not convenient for direct deployment without compilation.
@Eugene-Mark

**Comment by Jian-Zhang** [comment]
Where will be the lib for direct deployment? Do you mean user installed PMDK with tools provided by OS? @yao531441. @Eugene-Mark

**Comment by Eugene-Mark** [comment]
@Jian-Zhang The libjnipmdk.so is native library of rpmem shuffle plugin. Currently, we have integrated the library into the built java artifact, which is oap-rpmem-shuffle-java-0.9.0-jar-with-dependencies.jar. No need to load the library from specific path like /usr/local/lib/, it's hard coded and not self-contain.
