### ISSUE TITLE
[oap-native-sql] SortArraysToIndicesKernel: incorrect null ordering with multiple sort keys

### ISSUE THREAD

**Issue by zhztheplayer** [Intel-bigdata/OAP#1742]
We only use the first column among all sort keys for doing null ordering:

https://github.com/Intel-bigdata/OAP/blob/8878aa4a23c7c2fe6e288b9f36e799dce37a0c14/oap-native-sql/cpp/src/codegen/arrow_compute/ext/sort_kernel.cc#L231

With respect to SparkSQL / SQL standard, null ordering clause is specific to each sort specification, which means for example, following SQL is legal for execution:

```
ORDER BY col_a NULLS LAST col_b NULLS FIRST
```

Similar problem existing in ordering specification (ASC, DESC).

**Comment by xuechendi** [comment]
@rui-mo ，can you check on this

**Comment by zhouyuan** [comment]
fixed in master
