### ISSUE TITLE
[oap-native-sql] Error not reported when creating CodeGenerator instance

### ISSUE THREAD

**Issue by zhztheplayer** [Intel-bigdata/OAP#1743]
Related code:

https://github.com/Intel-bigdata/OAP/blob/8878aa4a23c7c2fe6e288b9f36e799dce37a0c14/oap-native-sql/cpp/src/codegen/code_generator_factory.h#L39-L56

It might be better to use arrow::Status convention instead.

**Comment by zhouyuan** [comment]
should be fixed now
