### ISSUE TITLE
Extend with a scalable cache meta store

### ISSUE THREAD

**Issue by offthewall123** [Intel-bigdata/OAP#1748]
Now oap schedule tasks according to cache locality, which in stored in a  in-memory hashmap.

For large scale cluster, there will be too much cache locality info.

**Comment by jikunshang** [comment]
Do we have any PR related? Or create some other issues?

**Comment by offthewall123** [comment]
It's related to Redis external DB.
master branch: https://github.com/Intel-bigdata/OAP/pull/1744
0.8 branch: https://github.com/Intel-bigdata/OAP/pull/1740

**Comment by jikunshang** [comment]
OK. Close this.
