### ISSUE TITLE
Could not find artifact io.pmem:pmemkv:jar:1.0.0 in maven repository

### ISSUE THREAD

**Issue by LuciferYang** [Intel-bigdata/OAP#1777]
It seems that `io.pmem:pmemkv:jar:1.0.0` has not been deployed to the central maven repository, when I execute

```
mvn clean install -DskipTests -pl oap-cache/oap -am
```

the compile error as follow:

```
[ERROR] Failed to execute goal on project oap-common: Could not resolve dependencies for project com.intel.oap:oap-common:jar:0.9.0: Could not find artifact io.pmem:pmemkv:jar:1.0.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```

How should I compile it now?

**Comment by LuciferYang** [comment]
cc @jerrychenhf

**Comment by yma11** [comment]
@LuciferYang This issue is fixed by PR https://github.com/Intel-bigdata/OAP/pull/1773 which is now merged in master. Please check again.

**Comment by LuciferYang** [comment]
@yma11 can  build success now, close this ~
