### ISSUE TITLE
[OAP-CACHE] Decouple hearbeat message and use conf to determine whether to report locailty information

### ISSUE THREAD

**Issue by Aaxida** [Intel-bigdata/OAP#1924]
We are using external DB to store cache locality info, but the old OAP report mechanism still reports cache locality to the driver through RPC. Need to decouple this.

1:Using external DB => not report cache locality to the driver through RPC. But still, need to report cache metrics to the driver through RPC.
2:Using report mechanism =>follow current behavior.

**Comment by zhixingheyi-tian** [comment]
As synced with Dingyu, this issue can be closed.
