### ISSUE TITLE
[oap-native-sql] Stability test failed when running TPCH for 10 rounds.

### ISSUE THREAD

**Issue by haojinIntel** [Intel-bigdata/OAP#1938]
We try to run TPCH with native-sql-engine for 10 rounds and q8.sql, q9.sql, q17.sql will failed in some rounds. The data scale is 1.5TB and the cluster contains one master and three workers. Per worker has 384GB memory. The configuration of spark is showed below:
![image](https://user-images.githubusercontent.com/44394375/99926502-ee2c3000-2d7c-11eb-90fb-25d479c38fdb.png)

And the error message from beeline is showed below:
![image](https://user-images.githubusercontent.com/44394375/99926717-92ae7200-2d7d-11eb-9d3f-d856953afc0a.png)

**Comment by haojinIntel** [comment]
@zhouyuan Please help to track this issue. Thanks!

**Comment by zhouyuan** [comment]
@haojinIntel thanks for the help! The backport patch should fix this issue. i'm doing some cleanups and will merge it back to 1.0
https://github.com/Intel-bigdata/OAP/pull/1933

**Comment by zhouyuan** [comment]
@haojinIntel  it looks like the stability is better after some backports and better turnings, can you please update the testing status here? thanks!
