### ISSUE TITLE
[SDLe][Native-SQL-engine]high vulnerabilities brought from Arrow 0.17.0 

### ISSUE THREAD

**Issue by HongW2019** [Intel-bigdata/OAP#1946]
Snyk code scanning on OAP branch-1.x-spark-3.x
![image](https://user-images.githubusercontent.com/30172512/99948177-fce20980-2db3-11eb-8d03-49a22cb9faa0.png)
![image](https://user-images.githubusercontent.com/30172512/99948425-695d0880-2db4-11eb-9595-5cbd8c6b1fe0.png)
![image](https://user-images.githubusercontent.com/30172512/99948594-a4f7d280-2db4-11eb-9a60-39962cf9b9b8.png)

**Comment by zhouyuan** [comment]
pending fix here, needs more verification on performance.
https://github.com/Intel-bigdata/arrow/pull/98

**Comment by zhouyuan** [comment]
@HongW2019 the arrow chanage is merged. can you please kindly to check again? thanks!

**Comment by HongW2019** [comment]
@zhouyuan  Sure, I will check now.
