### ISSUE TITLE
[OAP-CACHE] Plasma shows lower performance comparing with vanilla spark.

### ISSUE THREAD

**Issue by haojinIntel** [Intel-bigdata/OAP#1955]
For OAP-1.0, the data scale is 3TB and clusters contain 3 slaves and 1TB PMEM for each worker.  The performance of Plasma is 40% lower than vanilla spark. The  configuration of spark is showed below:

spark.executor.sql.oap.cache.external.client.pool.size 20
spark.yarn.historyServer.address vsr224:18080
spark.sql.broadcastTimeout 3600
spark.executor.memoryOverhead 2731
spark.sql.oap.mix.data.memory.manager plasma
spark.dynamicAllocation.executorIdleTimeout 3600s
spark.master yarn
spark.executor.memory 90g
spark.memory.offHeap.size 30g
spark.sql.autoBroadcastJoinThreshold 31457280
spark.deploy-mode client
spark.eventLog.dir hdfs://vsr224:9000/spark-history-server
spark.executor.sql.oap.cache.persistent.memory.initial.size 450g
spark.executor.cores 45
spark.kryoserializer.buffer.max       256m
spark.driver.memory 100g
spark.network.timeout 3600s
spark.memory.offHeap.enabled false
spark.eventLog.enabled true
spark.executor.instances 6
spark.sql.oap.index.directory /tmp
spark.speculation false
spark.sql.oap.dcpmm.free.wait.threshold 50000000000
spark.sql.oap.cache.guardian.free.thread.nums 4
spark.history.fs.logDirectory hdfs://vsr224:9000/spark-history-server
spark.oap.cache.strategy  external
spark.sql.extensions org.apache.spark.sql.OapExtensions
spark.executor.extraClassPath ./oap-cache-1.0.0-with-spark-3.0.0.jar:./oap-common-1.0.0-with-spark-3.0.0.jar
spark.history.fs.cleaner.enabled true
spark.sql.oap.external.cache.metaDB.impl               org.apache.spark.sql.execution.datasources.RedisClient
spark.sql.oap.external.cache.metaDB.address            10.1.0.124
spark.sql.oap.external.cache.metaDB.enabled            true
spark.driver.extraClassPath /opt/Beaver/OAP/oap_jar/oap-cache-1.0.0-with-spark-3.0.0.jar:/opt/Beaver/OAP/oap_jar/oap-common-1.0.0-with-spark-3.0.0.jar
spark.sql.oap.parquet.data.cache.enabled true
spark.kryoserializer.buffer           64m
spark.history.ui.port 18080
spark.files /opt/Beaver/OAP/oap_jar/oap-cache-1.0.0-with-spark-3.0.0.jar,/opt/Beaver/OAP/oap_jar/oap-common-1.0.0-with-spark-3.0.0.jar
spark.yarn.numa.enabled false
spark.serializer org.apache.spark.serializer.KryoSerializer
spark.authenticate false
spark.sql.warehouse.dir hdfs://vsr224:9000/spark-warehouse
spark.sql.inMemoryColumnarStorage.compressed true

**Comment by haojinIntel** [comment]
@offthewall123 @jikunshang Please help to track this performance issue.

**Comment by jikunshang** [comment]
Closed this one since plamsa could perform better than vanilla spark in oap nightly build.
