### ISSUE TITLE
[OAP-MLlib]Cannot get 5x performance benefit comparing with vanilla spark.

### ISSUE THREAD

**Issue by haojinIntel** [Intel-bigdata/OAP#1956]
For OAP-1.0. We try to measure the performance of Intel mllib. Our cluster contains 3 slaves and each nodes contain 384GB memory. The data scale is 250GB. The result shows as below:

Component | Configuration | Status | Succeeded Cases | Failed cases | baseline/s | optimized/s | Regression ratio/% | Regression cases | Details
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
oap-mllib | KMEANS_250GB_INTEL_MLLIB | SUCCEED | 1 | 0 | 347.061 | 467.932 | -25.8 | 1 | Details

The configuration of spark is showed below:
hibench.streambench.spark.checkpointPath /var/tmp
hibench.yarn.executor.num     12
hibench.spark.home       /opt/Beaver/spark
spark.default.parallelism     ${hibench.default.map.parallelism}
spark.files    /opt/Beaver/OAP/oap_jar/oap-mllib-1.0.0-with-spark-3.0.0.jar
spark.executor.extraClassPath     ./oap-mllib-1.0.0-with-spark-3.0.0.jar
hibench.streambench.spark.receiverNumber        4
spark.driver.memory 100g
hibench.streambench.spark.storageLevel 2
hibench.streambench.spark.batchInterval         100
spark.driver.extraClassPath       /opt/Beaver/OAP/oap_jar/oap-mllib-1.0.0-with-spark-3.0.0.jar
hibench.yarn.executor.cores   20
spark.executor.memory 65g
hibench.spark.master     yarn
hibench.streambench.spark.useDirectMode true
hibench.streambench.spark.enableWAL false
spark.sql.shuffle.partitions  200

**Comment by haojinIntel** [comment]
@xwu99 Please help to track the performance issue. Is the configuration reasonable?

**Comment by xwu99** [comment]
@haojinIntel It maybe reasonable. The performance scaling depends on feature number, sample number and the K you choose.
