### ISSUE TITLE
[SDLe][native-sql-engine] Issues from Static Code Analysis with Klocwork need to be fixed 

### ISSUE THREAD

**Issue by HongW2019** [Intel-bigdata/OAP#1979]
Issues from Static Code Analysis with Klocwork need to be fixed before OAP 1.0.0 release.
![image](https://user-images.githubusercontent.com/30172512/101561516-6ee75f00-3a00-11eb-95cd-15e5986a23dd.png)

**Comment by zhouyuan** [comment]
@HongW2019 FYI. just merged #2002

**Comment by HongW2019** [comment]
Got it, close it now. @zhouyuan
