### ISSUE TITLE
[OAP-CACHE] Error runing q32 binary cache

### ISSUE THREAD

**Issue by offthewall123** [Intel-bigdata/OAP#1981]
core dump running q32 using binary cache

**Comment by zhixingheyi-tian** [comment]
@offthewall123  mark this as "OAP 1.0"?

**Comment by offthewall123** [comment]
@zhixingheyi-tian No, it's 0.8 branch.

**Comment by jikunshang** [comment]
closed since PR got merged.

**Comment by jikunshang** [comment]
@HongW2019 reproduce this issue on branch-1.0. Analyze code again, need some more fix.

**Comment by offthewall123** [comment]
LGTM.
