### ISSUE TITLE
[OAP-Cache]When using Plasma Spark webUI OAP Tab cache metrics are not right  

### ISSUE THREAD

**Issue by lintonwang-intel** [Intel-bigdata/OAP#2028]
Run 10 GB Parquet TPC-DS webUI OAP cache statistics are not right. 
![image](https://user-images.githubusercontent.com/14993280/101717783-eab5da00-3ada-11eb-8511-73878dae6c21.png)
![image](https://user-images.githubusercontent.com/14993280/101717844-0a4d0280-3adb-11eb-9f2f-2b3b975029cb.png)

Also when run  data with index , Spark webUI OAP cache hit rate  are not right. 
![image](https://user-images.githubusercontent.com/14993280/101718039-60ba4100-3adb-11eb-875d-bfe42669d739.png)
![image](https://user-images.githubusercontent.com/14993280/101718169-a37c1900-3adb-11eb-8ae2-bf81c2431bc0.png)

**Comment by lintonwang-intel** [comment]
@offthewall123 please take a review~

**Comment by offthewall123** [comment]
@lintonwang-intel  Which branch?

**Comment by lintonwang-intel** [comment]
> @lintonwang-intel Which branch?

branch-1.0-spark-3.x

**Comment by jikunshang** [comment]
can we close this issue? @lintonwang-intel @HongW2019

**Comment by HongW2019** [comment]
Please help close it. @jikunshang
