### ISSUE TITLE
[oap-native-sql] Multiple issues while testing OAP 0.9.0 with spark 3.0.2 

### ISSUE THREAD

**Issue by kunal642** [Intel-bigdata/OAP#2098]
Hi OAP team,
Please find the details of the 2 issues below.
 
**Environment:**
* Local standalone cluster
* Java = 1.8.0_281
* Spark = 3.0.2 
* Hadoop = 3.1.4
* spark-defaults
![image](https://user-images.githubusercontent.com/11694130/111358006-dcfe8a80-86af-11eb-8707-19d7dc3e608a.png)
* OAP
![image](https://user-images.githubusercontent.com/11694130/111358247-2222bc80-86b0-11eb-951e-80a9b4060788.png)

**Issue1:** 
After enabling the 'com.intel.oap.ColumnarPlugin' insert into parquet table is failing with ArrayIndexOutOfBoundsException
![image](https://user-images.githubusercontent.com/11694130/111358766-b856e280-86b0-11eb-92ef-69cf1b773322.png)

**Issue2:**
1. Disable the 'com.intel.oap.ColumnarPlugin' extension
2. Insert data into tpcds parquet tables
3. Enable the 'com.intel.oap.ColumnarPlugin' extension
4. select count(*) from tpcds_parquet.store_sales;
![image](https://user-images.githubusercontent.com/11694130/111359364-6a8eaa00-86b1-11eb-9b70-09ac211b8b0a.png)
![image](https://user-images.githubusercontent.com/11694130/111359416-7e3a1080-86b1-11eb-901f-300efd80e5ed.png)

**Comment by kunal642** [comment]
@zhouyuan Please help me with this issue

**Comment by JkSelf** [comment]
@kunal642 
Sorry for the late reply. OAP 0.9 is an initial version that is not very stable. We have made a lot of improvements in stability and performance in OAP 1.0 + Spark 3.0. Is it convenient for you to try OAP 1.0 + Spark 3.0 in your environment?

**Comment by kunal642** [comment]
Hi @JkSelf After trying with 1.0 version the initial problem got resolved but the following exception is thrown.

![image](https://user-images.githubusercontent.com/11694130/112459801-3e93b880-8d84-11eb-896f-7832e799ef6b.png)

**Comment by kunal642** [comment]
@JkSelf I was able to run the same using datasource, earlier I was running through SQL. 
Silly mistake

Thank you for your help
