### ISSUE TITLE
Index creation support specify partition

### ISSUE THREAD

**Issue by xuanyuanking** [Intel-bigdata/OAP#232]
During the online scenario, we found that current index create only support all table partition and each creation cost too much resources. Also we may only need to keep a nearest 7 days data indexed instead of all partitions indexed. The index create and drop command change to:
```
CREATE SINDEX [IF NOT EXISTS] indexName ON tableName (col1 [ASC | DESC], col2, ...)
[USING (BTREE | BLOOM | BITMAP)] [PARTITION (partcol1=val1, partcol2=val2 ...)]

DROP INDEX [IF EXISTS] indexName on tableName [PARTITION (partcol1=val1, partcol2=val2 ...)]
```

**Comment by adrian-wang** [comment]
fixed in #247
