### ISSUE TITLE
System.setProperty(key, value) not working in cluster mode

### ISSUE THREAD

**Issue by linhong-intel** [Intel-bigdata/OAP#235]
in cluster mode, driver and workers are not in a same process. so `System.setProperty` is not working.

**Comment by lee-lei** [comment]
System class is from java.lang package. Therefore, the properties set by this approach will be valid only within one single JVM instance. SparkConf is used as the super set of System.setProperty. In my understanding, the properties set by SparkConf (default apporach is conf/spark-defaults.conf) will be valid across the multi JVM instances among all the worker nodes and the master node.  If we want to apply these kind of properties for all the executors and the driver, it's right solution to set it in conf/spark-defaults.conf. Thanks.

**Comment by linhong-intel** [comment]
In this Issue we need enable config by using
`SqlConf.setConf(key, value)`
and
`spark.sql("create table t using spn optinons(key value)")`

**Comment by lee-lei** [comment]
I understand your point now. There are two approaches to define the properties for both the driver and workers. One is statically added in conf/spark-defaults.conf or in additional property file from commandline. The other is added at runtime in order for developers to easily change or modify the properties even during the spark sql is running. I am checking how to support this feature elegantly. Thanks.

**Comment by lee-lei** [comment]
I will create another issue to clearly describe this problem. Meanwhile, I will focus other issues about ease for use of OAP at the beginning as the common user of this package. Thanks.
