### ISSUE TITLE
No Lease Exception on Parquet File Format in Index Building

### ISSUE THREAD

**Issue by linhong-intel** [Intel-bigdata/OAP#243]
Parquet data file is splittable while reading. So multiple tasks can access one index file.

**Comment by chenghao-intel** [comment]
A workaround is to disable the split reading for Parquet if index enabled?

**Comment by linhong-intel** [comment]
> A workaround is to disable the split reading for Parquet if index enabled?
Yes. This a record here to see if Daoyuan has a better solution. He is planing the Index refactoring.

**Comment by adrian-wang** [comment]
I'm planning to add an internal virtual column for "row id", and do group and sort in each file partition using DataSet API with the group key to be filename. Cool?
