### ISSUE TITLE
Write index more intensely

### ISSUE THREAD

**Issue by adrian-wang** [Intel-bigdata/OAP#256]
Currently we are using `UnsafeRow` to write index content, which is not very efficient in storage.

**Comment by linhong-intel** [comment]
I have one PR for this.

**Comment by linhong-intel** [comment]
I found UnsafeRow also consume a lot of memory.
I tried `val v = InternalRow.fromSeq(iterator.next().toSeq(keySchema))` and tested on cluster. Memory usage decreased a lot.

**Comment by adrian-wang** [comment]
I think you are saving memory because you are not doing `copy()`

**Comment by linhong-intel** [comment]
Nope. the reason is UnsafeRow need more members to represent a row, then more memory.

For one UnsafeRow object, it will use 3 Int, 1 Long plus the real data as member.
For InternalRow, only the real data is member.

**Comment by linhong-intel** [comment]
I tried only removing `copy()` nothing changed.

**Comment by adrian-wang** [comment]
removing `copy()` will lead to a bunch of errors; `UnsafeRow` using more memory is the same of storage, since they are the same from binary.
