### ISSUE TITLE
Index Statistics is not configurable

### ISSUE THREAD

**Issue by linhong-intel** [Intel-bigdata/OAP#277]
After refactor, seems some Index Statistics parameters are hard-coded or not used.
For example:
SPINACH_FULL_SCAN_THRESHOLD = hard coded to 0.8
SPINACH_STATISTICS_TYPES = not used
SPINACH_STATISTICS_SAMPLE_RATE = hard coded to 0.1
SPINACH_BLOOMFILTER_MAXBITS = hard coded to 1 << 20
SPINACH_BLOOMFILTER_NUMHASHFUNC = hard coded to 3

@gfl94 Can you confirm with this?

**Comment by gfl94** [comment]
Statistics parameters can be configured through `StatisticsManager` object method, please refer to [code here](https://github.com/Intel-bigdata/OAP/blob/master/src/main/scala/org/apache/spark/sql/execution/datasources/spinach/statistics/StatisticsManager.scala#L180).

**Comment by linhong-intel** [comment]
>Statistics parameters can be configured through `StatisticsManager` object method, please refer to [code here](https://github.com/Intel-bigdata/OAP/blob/master/src/main/scala/org/apache/spark/sql/execution/datasources/spinach/statistics/StatisticsManager.scala#L180).

Thanks, but I thinks it's better to config it through Configuration. I made the PR #281 enabled this, you can review it.
