### ISSUE TITLE
Upgrade Spark version to 2.1.0

### ISSUE THREAD

**Issue by songzhan01** [Intel-bigdata/OAP#307]
The latest version of OAP is based on Spark release 2.0.2.  Spark 2.1.0 has been released for more than half a year, and it brings lots of new features, performance improvement and bug fixes. So we should bump up the dependent Spark version to 2.1.0.

**Comment by songzhan01** [comment]
https://docs.google.com/document/d/1oZa_NjWKR-5TVD_Awu2sAz4Wb6HvNs6Oh5biJyXqbaY/edit?usp=sharing

**Comment by adrian-wang** [comment]
BTW, I think 2.1.1 would be better than 2.1.0

**Comment by songzhan01** [comment]
Okay

**Comment by adrian-wang** [comment]
Finished by #337
