### ISSUE TITLE
OapException - Cannot instantiate class OapDataFile

### ISSUE THREAD

**Issue by linhong-intel** [Intel-bigdata/OAP#331]
Oap should handle non-OapDataFile properly.

**Comment by adrian-wang** [comment]
Can you update this with reproduce steps?

**Comment by linhong-intel** [comment]
Will update it this week.

**Comment by adrian-wang** [comment]
any update?

**Comment by linhong-intel** [comment]
sorry, i forgot this issue. close it for now.
