### ISSUE TITLE
Add index hit state for sql

### ISSUE THREAD

**Issue by LuciferYang** [Intel-bigdata/OAP#383]
We need add index hit state for sql like "is hit index？" or "What index columns were hit？" to let us do white-box testing.

**Comment by yueawang** [comment]
What if we list these info in a DDL's output, like explain or a new one? Or you want a API to be called in runtime, so you can do sth accordingly?

**Comment by adrian-wang** [comment]
@lee-lei I believe lei has done some changes related to this in #318

**Comment by LuciferYang** [comment]
@yueawang @adrian-wang yeap, i want a api can be called in runtime for white-box testing to ensure our test case hit index, @TigerSong will do sth about this.

**Comment by lee-lei** [comment]
@LuciferYang The #318 can achieve your needs. It's using the extended Spark listener(SparkListenerOapIndexInfoUpdate) and corresponding event callback(onOapIndexInfoUpdate) to monitor the index info on the executors. I may need to upload a PR to just expose this event callback API to the developers like you guys. Thanks.

**Comment by LuciferYang** [comment]
@lee-lei  There are two questions about #318 :
1、Is #318 suitable for read parquet file with oap?
2、How to use  API to get index use info after sql execution？This is a user requirement in production environment. User wants to know if the SQL he runs use index.

**Comment by lee-lei** [comment]
@adrian-wang I see. Thanks for clarifying the requirements.
