### ISSUE TITLE
Same index can be create twice without exception

### ISSUE THREAD

**Issue by linhong-intel** [Intel-bigdata/OAP#389]
Sql:
`CREATE OINDEX IF NOT EXISTS store_sales_index ON store_sales (ss_item_sk) USING BTREE`
Reason:
`IF NOT EXISTS` will allow user create same index
Proposed Fix:
1. Just do nothing and return directly.
2. Rewrite all current index.
3. behave like refresh.

**Comment by Moonlit-Sailor** [comment]
fixed by #394
