### ISSUE TITLE
Null value in Btree and bitmap index cause exception

### ISSUE THREAD

**Issue by adrian-wang** [Intel-bigdata/OAP#397]
`writeBasedOnDataType` do not support write null value, which is used in bitmap and btree index writing.

Possible solutions:
1. find some way to write null
2. ignore `null` in the multi hash map when building tree schema, any one search for `null` can find that at the beginning of `rowIdList`.

I prefer solution 2.

BTW, current writing will cause pattern matching for every value it writes, which is inefficient. we should pass the datatype as parameter to eliminate this pattern match in `writeBasedOnDataType`.

**Comment by linhong-intel** [comment]
closed by #438
