### ISSUE TITLE
Combining Index 

### ISSUE THREAD

**Issue by LuciferYang** [Intel-bigdata/OAP#399]
Plan to implement combining index. Follow link is design documentation：
https://docs.google.com/document/d/1hSvRd8muxTlNd66kBpP-c-U0ClPx6Qpn-hGNdqUTBKk/edit?usp=sharing

**Comment by LuciferYang** [comment]
@adrian-wang @linhong-intel @xuanyuanking @linhong-intel

**Comment by adrian-wang** [comment]
Fixed by #439
