### ISSUE TITLE
Avoid using ChunkedByteBuffer in the OAP code

### ISSUE THREAD

**Issue by chenghao-intel** [Intel-bigdata/OAP#400]
When I review the code, I saw many place has the code like `ChunkedByteBuffer.toArray`, which supposed to be the memory copies, and may cause performance / gc and even OOM failures, I will suggesting to use something else like a simple wrapper with the basic function like `getInt` etc., this wrapper will hide the details either offheap memory or byte[] on-heap.

**Comment by chenghao-intel** [comment]
@linhong-intel

**Comment by chenghao-intel** [comment]
this can be in a separated branch.

**Comment by linhong-intel** [comment]
Using ChunkedByteBuffer is to utilize spark's BlockManager to manage Cache. Since we will change back to Guava for Cache Manager, this issue will not exists after that.

**Comment by linhong-intel** [comment]
Fixed by #419
