### ISSUE TITLE
Create a SharedOapContext to unify test suite.

### ISSUE THREAD

**Issue by linhong-intel** [Intel-bigdata/OAP#443]
Currently, we extends `SharedSQLContext` for testing.
But we need to override some configs to enable OAP features.

So let's create a `SharedOapContext` which extends `SharedSQLContext` and do the configs.
Then all test suites extends SharedOapContext to avoid duplicate setting.

**Comment by linhong-intel** [comment]
assign to @LuciferYang first.

**Comment by LuciferYang** [comment]
ok~

**Comment by adrian-wang** [comment]
fixed by #452
