### ISSUE TITLE
Re-enable statistics for Bitmap Index

### ISSUE THREAD

**Issue by linhong-intel** [Intel-bigdata/OAP#450]
Should be a follow up of PR #416

> BitMap version will be updated after bit map index really use unsafe way to access data.

**Comment by LuciferYang** [comment]
assign to @songzhan01  first.

**Comment by adrian-wang** [comment]
@songzhan01 Please note that this should be done after bitmap index really use unsafe way to access data.

**Comment by linhong-intel** [comment]
@songzhan01 any update?

**Comment by lee-lei** [comment]
This issue will be addressed by the PR #539. Thanks.

**Comment by songzhan01** [comment]
This issue had been addressed by the PR #539, so close it.
