### ISSUE TITLE
Partial Load Bitmap Entry List

### ISSUE THREAD

**Issue by songzhan01** [Intel-bigdata/OAP#483]

**Comment by linhong-intel** [comment]
Currently, BitmapIndex loads the all bitmap entries into a whole fiber.
Baidu @songzhan01 proposed to have a partial loading for this entry fiber.
The design is: 1 entry -> 1 fiber

@songzhan01  will test the bitmap index size in their production environment to decide if this is needed.

**Comment by songzhan01** [comment]
Use a parquet file to test.
file size: 1113285613 bytes
record number: 425400
unique key (cmatch): 77
The result:
the size of index file using Baidu internal version: 4099602 bytes
the size of index file using  oap master: 429801 bytes

**Comment by linhong-intel** [comment]
thanks @songzhan01 

BTW, btree index is 2M on the same column

**Comment by songzhan01** [comment]
The size of bitmap index file using oap maste is relatively small，close this issue.
