### ISSUE TITLE
"assertion failed: No plan for MetastoreRelation" with spark-sql

### ISSUE THREAD

**Issue by linhong-intel** [Intel-bigdata/OAP#484]
use spark-shell, there is no problem.

Suspect this is caused by `OapEnv`

My findings:
In `SparkSQLEnv`, `HiveSessionState` is used, and `HiveStrategies` is applied to `SparkPlanner`
In `OapEnv`, `OapSessionState` is used, and `OapStrategies` is applied to `SparkPlanner`

`OapStrategies` DOES NOT contain `HiveStrategies`
In `HiveStrategies` there is a `HiveTableScans` used to plan `MetastoreRelation`

**Comment by linhong-intel** [comment]
found in baidu's production environment, don't have a way to easily reproduce in local env.

**Comment by adrian-wang** [comment]
`OapStrategies` should include `HiveStrategies`, if we enable hive support.

**Comment by linhong-intel** [comment]
fixed #501
