### ISSUE TITLE
too many open files error during unit test.

### ISSUE THREAD

**Issue by linhong-intel** [Intel-bigdata/OAP#500]
need go through the code to close unnecessary files.

**Comment by adrian-wang** [comment]
Just raise your ulimit a little bit.

**Comment by adrian-wang** [comment]
will check if fixed now.

**Comment by adrian-wang** [comment]
This problem still persists when ulimit is around 2000. When set ulimit to 4000, it is gone.

**Comment by adrian-wang** [comment]
This problem can be resolved when #770 #771 #772 merged.

**Comment by adrian-wang** [comment]
Let's close this since all three pull requests has merged.
