### ISSUE TITLE
[0.3.0 QA] Confirm statistics performance

### ISSUE THREAD

**Issue by carsonwang** [Intel-bigdata/OAP#514]
Reporter: Yang
To confirm statistics performance, will disable it and compare results to current version on large results case.

**Comment by chenghao-intel** [comment]
This is very critical as the index statistics is the key feature of 0.3.

**Comment by xuyangit** [comment]
As for this, I have confirmed that for large case (e.g, Q1 and Q2), the stats has skipped using indexes for some partitions.  The data shows after disabling stats, the performance of using indexes will be worse than full scanning.
Test results of enabling stats:                                                    
+-----------------+-----+-----+-----+---------+                                  
|               Q1|T1/ms|T2/ms|T3/ms|Median/ms|                                  
+-----------------+-----+-----+-----+---------+                                  
|   oap-with-index|36298|20052|20866|    20866|                                  
|oap-without-index|33136|21531|19670|    21531|                                  
+-----------------+-----+-----+-----+---------+                                  
+-----------------+-----+-----+-----+---------+                                  
|               Q2|T1/ms|T2/ms|T3/ms|Median/ms|                                  
+-----------------+-----+-----+-----+---------+                                  
|   oap-with-index|18752|16892|17793|    17793|                                  
|oap-without-index|18325|17143|17026|    17143|                                  
+-----------------+-----+-----+-----+---------+                                  
+-----------------+-----+-----+-----+---------+                                  
|               Q3|T1/ms|T2/ms|T3/ms|Median/ms|                                  
+-----------------+-----+-----+-----+---------+                                  
|   oap-with-index|14914| 7476| 7694|     7694|                                  
|oap-without-index|14602|12556| 7881|    12556|                                  
+-----------------+-----+-----+-----+---------+                                  
+-----------------+-----+-----+-----+---------+                                  
|               Q4|T1/ms|T2/ms|T3/ms|Median/ms|                                  
+-----------------+-----+-----+-----+---------+                                  
|   oap-with-index| 8003| 6612| 8484|     8003|                                  
|oap-without-index|10167| 6865| 6575|     6865|                                  
+-----------------+-----+-----+-----+---------+ 

Test results of disabling stats:                                                     
+-----------------+-----+-----+-----+---------+                                  
|               Q1|T1/ms|T2/ms|T3/ms|Median/ms|                                  
+-----------------+-----+-----+-----+---------+                                  
|   oap-with-index|35300|26779|20930|    26779|                                  
|oap-without-index|35601|20942|22128|    22128|                                  
+-----------------+-----+-----+-----+---------+                                  
+-----------------+-----+-----+-----+---------+                                  
|               Q2|T1/ms|T2/ms|T3/ms|Median/ms|                                  
+-----------------+-----+-----+-----+---------+                                  
|   oap-with-index|34725|22563|25722|    25722|                                  
|oap-without-index|16530|16201|17543|    16530|                                  
+-----------------+-----+-----+-----+---------+                                  
+-----------------+-----+-----+-----+---------+                                  
|               Q3|T1/ms|T2/ms|T3/ms|Median/ms|                                  
+-----------------+-----+-----+-----+---------+                                  
|   oap-with-index|25415|11038|10678|    11038|                                  
|oap-without-index|14675| 7206| 8581|     8581|                                  
+-----------------+-----+-----+-----+---------+                                  
+-----------------+-----+-----+-----+---------+                                  
|               Q4|T1/ms|T2/ms|T3/ms|Median/ms|                                  
+-----------------+-----+-----+-----+---------+                                  
|   oap-with-index|16281| 9937| 9993|     9993|                                  
|oap-without-index|14967| 7397| 6808|     7397|                                  
+-----------------+-----+-----+-----+---------+

**Comment by xuyangit** [comment]
The problem i'm a little confused is that, the performance of full scan the table for using indexes (without stats) and naive solution is similar, while for big cases like $attr < 30000000, they differ a lot.

**Comment by xuyangit** [comment]
As previous discussion shows, full scan (i.e., select * from table) won't trigger use of indexes. Thus have changed Q1 to select * from table where attr < Int.MaxValue. This shows different results compared to previous ones, where both solutions have no big difference. This issue can be closed now as the performance of our stats can be confirmed now.
+-----------------+-----+-----+-----+---------+                                  
|               Q1|T1/ms|T2/ms|T3/ms|Median/ms|                                  
+-----------------+-----+-----+-----+---------+                                  
|   oap-with-index|53131|36327|36216|    36327|                                  
|oap-without-index|37516|24901|24904|    24904|                                  
+-----------------+-----+-----+-----+---------+

**Comment by xuyangit** [comment]
@carsonwang

**Comment by carsonwang** [comment]
Thanks @xuyangit  for the detailed report.
