### ISSUE TITLE
[0.3.0 QA] For bitmap and tree index, oap-without-index result should be similar in each Query

### ISSUE THREAD

**Issue by carsonwang** [Intel-bigdata/OAP#516]
Reporter: Linhong
For bitmap and tree index, oap-without-index result should be similar in each Query.
But sometimes, it varies a lot. For example, 100g + 80g + 4 environment, Q11. Result is 12168 vs 3003

**Comment by Moonlit-Sailor** [comment]
Bit map's Q11 is different from B+ tree 's Q11, they are different queries.

**Comment by lee-lei** [comment]
For bitmap index, from the data (benchmark_res_tpcds200_40g_80g_8_executor, benchmark_res_tpcds200_100g_80g_4_executor and res_select_for_each_tpcds200), oap-without-index data looks like that they are normal as expectation except very rare corner cases(one or two run of data).

**Comment by linhong-intel** [comment]
@Moonlit-Sailor Thanks.
Is there any place to see the command for each query

**Comment by linhong-intel** [comment]
I'll take this since it may be an invalid issue.

**Comment by xuyangit** [comment]
@carsonwang ,I have finished code cleaning and will do some tests afterwards. Could we create a branch to  see the version with benchmark?

**Comment by carsonwang** [comment]
@xuyangit , yes I plan to create a 0.3.0 branch and we can do the benchmark on that branch. Is that what you want?

**Comment by xuyangit** [comment]
@carsonwang ,ok

**Comment by linhong-intel** [comment]
I checked the query command.
Bitmap and BTree use different column and filter to test. so no need to compare the result.
close
