### ISSUE TITLE
[0.3.0 QA] parquet-with-index is slower than the parquet-without-index

### ISSUE THREAD

**Issue by carsonwang** [Intel-bigdata/OAP#517]
Reporter: Hao
parquet-with-index is slower than the parquet-without-index, in all of the BitMap Index benchmark, and part of the BTree Index. The index statistic is supposed to work, but it doesn’t?

**Comment by carsonwang** [comment]
Is this duplicate to #511,  @Moonlit-Sailor ?

**Comment by Moonlit-Sailor** [comment]
yeah, they are partly overlapped, but we could not infer whether it is caused by statistic or parquet vectorization

**Comment by carsonwang** [comment]
Thanks @Moonlit-Sailor . Yes, this is what we need to investigate for the issue to see if it is caused by statistic or parquet vectorization or something else. I'll close this as duplicate as the problem description is actually the same.
