### ISSUE TITLE
[0.3.0 QA] flaky unit test "test Simple Cache Strategy"

### ISSUE THREAD

**Issue by carsonwang** [Intel-bigdata/OAP#520]
Sometime it fails. 
- test Simple Cache Strategy *** FAILED ***
  fiberCache.isDisposed was false (FiberCacheManagerSuite.scala:254)
https://travis-ci.org/Intel-bigdata/OAP/builds/329340068?utm_source=github_status&utm_medium=notification

**Comment by carsonwang** [comment]
@linhong-intel,  it seems sleep(10) is too less?

**Comment by linhong-intel** [comment]
very likely. I'm upload a PR to increase this.

**Comment by linhong-intel** [comment]
closed by #521
