### ISSUE TITLE
Performance Regression due to cache machenism.

### ISSUE THREAD

**Issue by yueawang** [Intel-bigdata/OAP#533]
One perf regression was found, the root cause is the lock scope of cache.get() covers the file read which in result make all following gets waiting in line.

I did not come up with a perfect solution, few candidates are listed below, but all of them have few artifacts.
1. Reduce synchronized scope to leave file system operation alone.
2. Use different lock according to different purposes (i.e. hit+run/miss+load)
3. Separate file loading to other thread, basically it is to make logic & data run on different paths.

However, things gonna be easier if we can take few more assumptions like no 2 or more threads load (read is ok) same fiber simultaneously.

**Comment by carsonwang** [comment]
Resolved by #538
