### ISSUE TITLE
OAP does not support "STORED AS OAP"

### ISSUE THREAD

**Issue by yueawang** [Intel-bigdata/OAP#545]
So far we can not store OAP file by thrift-server DDL.

**Comment by carsonwang** [comment]
There are two ways to create a table. One is "CREATE TABLE ... USING ..." which is used to create datasource table and OAP supports it. Another one is "CREATE TABLE ... ROW FORMAT ... STORED AS ..." which is used to create a Hive serde table. It requires an inputFormat, outputFormat and a serde, for example like parquet:
```
    "parquet" ->
      HiveSerDe(
        inputFormat = Option("org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat"),
        outputFormat = Option("org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat"),
        serde = Option("org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe")),
```
This is actually for Hive serde table not datasource table. So I am closing this as won't support.
