### ISSUE TITLE
Executor with plenty cores has high memory consumption and is stuck in job running.

### ISSUE THREAD

**Issue by yueawang** [Intel-bigdata/OAP#546]
Spark in yarn mode, one executor has for example 64 cores, 128 GB memory.
When build index or full scan a table. We see a huge number of GC. that's because 64 cores are working in parallel and each of which requires a lot of memory, then we can see lots of GC and the job is stuck.
So far it is recommended that use fewer cores, comparing to all cores in one work node, to build the index. And when query sth, itis less possible to do sort of full scan.
We need more detailed information to solve this. Further steps include:
1. Detail memory profile of single task to guide memory optimization.
2. Control memory consumption especially in parallel mode with lots of cores.
3. Brainstorming: adaptive execution on high memory consumption tasks, etc...

**Comment by carsonwang** [comment]
We made configuration guide in readme.
