### ISSUE TITLE
Simplify DataFile Api

### ISSUE THREAD

**Issue by LuciferYang** [Intel-bigdata/OAP#553]
DataFile Api as following code:

`abstract class DataFile {
  def path: String
  def schema: StructType
  def configuration: Configuration
  def context: Option[VectorizedContext]

  def createDataFileHandle(): DataFileHandle
  def getFiberData(groupId: Int, fiberId: Int, conf: Configuration): FiberCache
  def iterator(conf: Configuration, requiredIds: Array[Int]): Iterator[InternalRow]
  def iterator(conf: Configuration, requiredIds: Array[Int], rowIds: Array[Int]):
  Iterator[InternalRow]
  def getDictionary(fiberId: Int, conf: Configuration): Dictionary
}`

I think It has the following problems:

1. we define iterator method with configuration parameter which is same reference with configuration of constructor, should we remove it from method parameters？

2. the method getDictionary only use by OapDataFile, It is more suitable as an internal method of OapDataFile

**Comment by carsonwang** [comment]
Thanks @LuciferYang. The proposed changes looks reasonable to me. Also ping @linhong-intel for comments in case we missed something.

**Comment by linhong-intel** [comment]
good to me. can you also add the `close` for the api?

**Comment by LuciferYang** [comment]
@linhong-intel we close resources use oapiterator.close method now，move to datafile?

**Comment by linhong-intel** [comment]
@LuciferYang Get your point.

**Comment by LuciferYang** [comment]
#569 Completed this work
