### ISSUE TITLE
isNotNull may trigger hit-index in any condition 

### ISSUE THREAD

**Issue by TigerSong** [Intel-bigdata/OAP#555]
I find in most cases, a condition will be added a isNotNull filter. But maybe the original filter is not suitable for index.

for Example. 
string a;  select  xxx from xxx where a > 12; 

the SQL's corresponding Spark-Plan:  isNotNull(a) && cast(a#3 as double) > 12. Cast will be filtered, and isNotNull will trigger index. it seems unreasonable.

**Comment by yueawang** [comment]
Is this a bitmap index??
In theory, statistics check should skip IsNotNull as it has 100% hit rate.

**Comment by Moonlit-Sailor** [comment]
I'll pick this issue, since I implemented `Filter` optimize and process

**Comment by adrian-wang** [comment]
@Moonlit-Sailor the solution we just discussed offline, should better target 0.4.0. for 0.3.0 I think we can use the workaround.

**Comment by Moonlit-Sailor** [comment]
alright

**Comment by TigerSong** [comment]
@yueawang You are right. task won't use index for statistic check. But when for ParquetFileFormat, it can't use VectorizedColumnReader, and will run slower.

**Comment by yueawang** [comment]
I see @TigerSong , I did not consider this kind of issue ago. It's OK to remove this support, as the loss is just a corner case which rarely happens.

**Comment by adrian-wang** [comment]
Thanks @TigerSong for reporting this, since #558 is merged, would you mind closing #557 ?

**Comment by TigerSong** [comment]
#558 has fixed it.
