### ISSUE TITLE
Force release leaked FiberCache

### ISSUE THREAD

**Issue by linhong-intel** [Intel-bigdata/OAP#556]
For some reasons, FiberCache may never be released:
1. iterator is not fully read, so release is not called.
2. task is killed or throws exception, then all used fibers are not released.
In current code, this will cause OOM of executor, and reschedule executor.

Another solution(Workaround) is:
Give each fiber a timestamp in CacheGuardian. Force release fiber after a timeout.
This will avoid OOM but there is a small chance may cause "access a freed fiber" and reschedule task

With the compare, reschedule task is better.

**Comment by carsonwang** [comment]
Let's discuss other options before doing this. Force releasing that causes task failures could be bad experience for users.

**Comment by carsonwang** [comment]
One thing we can improve in the code is to release the fibers in `finally` so they will be released even if any exception occurs.

**Comment by linhong-intel** [comment]
@carsonwang 
sure. This ticket is just a remainder.
Since OOM caused executor reschedule is also a problem need be discussed.

**Comment by yueawang** [comment]
If OOM happens, will the executor restart (by yarn??)??

**Comment by carsonwang** [comment]
This has been resolved.
