### ISSUE TITLE
build with sbt

### ISSUE THREAD

**Issue by clayms** [Intel-bigdata/OAP#562]
Is it possible to build oap with sbt? 

What libraryDependencies do I need for the `build.sbt` file?

Thanks.

**Comment by clayms** [comment]
found the list `pom.xml`

**Comment by adrian-wang** [comment]
you can refer to Spark's sbt build process.

**Comment by carsonwang** [comment]
Is there anything that prevent you using `mvn`?

**Comment by clayms** [comment]
Thanks @adrian-wang .
I added `resolvers += Resolver.mavenLocal` to my `build.sbt`  file which downloaded the maven plugins as dependencies, but I am still getting the same 12 errors.

**Comment by clayms** [comment]
@carsonwang corporate IT

**Comment by carsonwang** [comment]
Close this. sbt is not officially supported by OAP but you can enable it yourself.
