### ISSUE TITLE
Add isNotNull back when parquetFileFormat calls hasAvailableIndex after we have vectorized reader

### ISSUE THREAD

**Issue by carsonwang** [Intel-bigdata/OAP#567]
In 0.3 release, we ignored isNotNull when parquetFileFormat calls hasAvailableIndex. We may consider add it back after parquet vectorized reader is merged. Please refer #555

**Comment by LuciferYang** [comment]
After we have parquet vetorized reader，perhaps we can read parquet file use oapfileformat directly when oap meta file exists and remove hasAvailableIndex method.
Could we read parquet file use oap format if oap meta file not exists?

**Comment by carsonwang** [comment]
isNotNull  is not used and close it
