### ISSUE TITLE
Fix compile waring of Scala dependency version 

### ISSUE THREAD

**Issue by LuciferYang** [Intel-bigdata/OAP#587]
[WARNING]  Expected all dependencies to require Scala version: 2.11.8
[WARNING]  com.intel.ssg.bdt:oap:0.4.0-SNAPSHOT requires scala version: 2.11.8
[WARNING]  com.intel.ssg.bdt:oap:0.4.0-SNAPSHOT requires scala version: 2.11.8
[WARNING]  org.scala-lang:scala-compiler:2.11.8 requires scala version: 2.11.8
[WARNING]  org.scala-lang:scala-reflect:2.11.8 requires scala version: 2.11.8
[WARNING]  org.scala-lang.modules:scala-xml_2.11:1.0.4 requires scala version: 2.11.4
[WARNING] Multiple versions of scala libraries detected!

**Comment by adrian-wang** [comment]
```
[INFO] +- org.scala-lang:scala-compiler:jar:2.11.8:compile
[INFO] |  +- org.scala-lang:scala-reflect:jar:2.11.8:compile
[INFO] |  +- org.scala-lang.modules:scala-xml_2.11:jar:1.0.4:compile
[INFO] |  \- org.scala-lang.modules:scala-parser-combinators_2.11:jar:1.0.4:compile
```
scala-compiler 2.11.8 depends on scala-xml_2.11 of version 1.0.4, while 1.0.4 scala-xml depends on 2.11.4 scala-compiler.

**Comment by LuciferYang** [comment]
can we  specify scala-xml_2.11 version to let all dep use scala 2.11.8?

**Comment by LuciferYang** [comment]
org.scala-lang.modules:scala-xml_2.11:jar:1.0.6 will dep scala 2.11.8
