### ISSUE TITLE
Parquet DataFileHandle should be postponed until necessary

### ISSUE THREAD

**Issue by linhong-intel** [Intel-bigdata/OAP#630]
found by @LuciferYang

**Comment by LuciferYang** [comment]
If a task get a empty RowIds, in spinach version it will cost aboud 80ms, but in oap if we cache DataFileHandle(parquet footer) for every task at any time, the task time will increase about 0.5s ~ 0.8s, It depends on the pressure of dfs.

**Comment by linhong-intel** [comment]
fixed by #631

**Comment by LuciferYang** [comment]
Thx ~ @linhong-intel
