### ISSUE TITLE
Follow #640 Optimization commitJob stage of CreateIndex Job 

### ISSUE THREAD

**Issue by LuciferYang** [Intel-bigdata/OAP#643]
#640 make sure build index job write result to temporary dir first , then rename temporary result to target dir at commitJob stage, but I found that we create index of one day partition data cost about 180s use 80 cores, but commitJob cost about 90s because job has 1.5w inputfile and commit stage  will do 1.5w ls operation (get task result file name) and 1.5w rename operation (rename task result to target dir). if parallelism of the job increase, 'commit job time/ job run time' will increase.

**Comment by LuciferYang** [comment]
@linhong-intel

**Comment by gczsjdy** [comment]
@LuciferYang Will you do this? I'm also interested. : )

**Comment by LuciferYang** [comment]
@gczsjdy yep, there is a prototype of patch, I'll give a pr this week, then we can discuss it feasibility~

**Comment by LuciferYang** [comment]
@gczsjdy  #689 is the key part of the code, next step I'll add some strategies to open this feature when the number of files is huge.
