### ISSUE TITLE
DropIndexCommand bug

### ISSUE THREAD

**Issue by LuciferYang** [Intel-bigdata/OAP#644]
For FilterSuite 'test refresh in oap format on a partition' test case, test data has 3 partition: `b=1, b=2, b=3`, we create index at partition b=1 and b =2 to test refresh, if we run  `drop oindex index1 on t_refresh` cmd after case, it will tell me `Index index1 does not exist on CatalogTable`.

The error stack as follow:
`Index index1 does not exist on CatalogTable(
	Table: `default`.`t_refresh`
	Created: Fri Mar 30 06:11:45 PDT 2018
	Last Access: Wed Dec 31 15:59:59 PST 1969
	Type: MANAGED
	Schema: [StructField(a,IntegerType,true), StructField(b,IntegerType,true)]
	Provider: oap
	Partition Columns: [`b`]
	Storage(Location: file:/Users/yangjie/SourceCode/github/oap-mine/spark-warehouse/t_refresh)
	Partition Provider: Catalog);
org.apache.spark.sql.AnalysisException: Index index1 does not exist on CatalogTable(
	Table: `default`.`t_refresh`
	Created: Fri Mar 30 06:11:45 PDT 2018
	Last Access: Wed Dec 31 15:59:59 PST 1969
	Type: MANAGED
	Schema: [StructField(a,IntegerType,true), StructField(b,IntegerType,true)]
	Provider: oap
	Partition Columns: [`b`]
	Storage(Location: file:/Users/yangjie/SourceCode/github/oap-mine/spark-warehouse/t_refresh)
	Partition Provider: Catalog);
	at org.apache.spark.sql.execution.datasources.oap.index.DropIndexCommand$$anonfun$run$9.apply(indexPlans.scala:247)
	at org.apache.spark.sql.execution.datasources.oap.index.DropIndexCommand$$anonfun$run$9.apply(indexPlans.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.sql.execution.datasources.oap.index.DropIndexCommand.run(indexPlans.scala:234)`

I think it's a bug.

**Comment by chenghao-intel** [comment]
I think we also need to drop the index in partitions.

**Comment by chenghao-intel** [comment]
that's great, thank you @LuciferYang

**Comment by adrian-wang** [comment]
@LuciferYang drop oindex if exists will just do nothing in this case. To drop these indices cascade, we have to iterate all the partitions. Does this make sense?

**Comment by LuciferYang** [comment]
@adrian-wang Get ur point,I'll try to do this optimization
