### ISSUE TITLE
OAP-Spark  FileFormat

### ISSUE THREAD

**Issue by Moonlit-Sailor** [Intel-bigdata/OAP#647]
### OAP 0.3.0 - Spark 2.1.0 API change -   FileFormat (until commit 5b63c970bf8f6b)

_org.apache.spark.sql.execution.datasources.FileFormat:_
**Before:**  
`def inferSchema(sparkSession: SparkSession, options: Map[String, String],files: Seq[FileStatus]): Option[StructType]`
**After:**     
`def inferSchema: Option[StructType] `
**Reason:** 
Easy storage for data schema, we need to load schema from disk directly

**Comment by adrian-wang** [comment]
#700 explains another change to `FileFormat`.

**Comment by gczsjdy** [comment]
@adrian-wang @linhong-intel Sorry but why this change? Explanation is a little rough...
