### ISSUE TITLE
OAP-Spark  FileSourceStrategy

### ISSUE THREAD

**Issue by Moonlit-Sailor** [Intel-bigdata/OAP#649]
### OAP 0.3.0 - Spark 2.1.0 API change -   FileSourceStrategy (until commit 5b63c970bf8f6b)

_org.apache.spark.sql.execution.datasources.FileSourceStrategy_
**Before:** 
**After:**
Add file format process in `apply()` method. 
**Reason:**
Make oap index compatible with parquet format, and initialize file format

**Comment by adrian-wang** [comment]
We can register `OapStrategies` in a unified place.

**Comment by zhixingheyi-tian** [comment]
About spark2.3, changes are the same.

**Comment by LuciferYang** [comment]
Or we can try to use SparkSessionExtensions to register OapFileSourceStrategy

**Comment by LuciferYang** [comment]
after #995 no longer modify this file
