### ISSUE TITLE
OAP-Spark  UnsafeRow

### ISSUE THREAD

**Issue by Moonlit-Sailor** [Intel-bigdata/OAP#651]
### OAP 0.3.0 - Spark 2.1.0 API change -   UnsafeRow  (until commit 5b63c970bf8f6b)

_org.apache.spark.sql.catalyst.expressions.UnsafeRow_
**Before:**
**After:**
Add UnsafeRow.setNumFields
**Reason:**
Read UnsafeRow from disk thread safely.

**Comment by adrian-wang** [comment]
resolved by #216
