### ISSUE TITLE
OAP-Spark  BitSet

### ISSUE THREAD

**Issue by Moonlit-Sailor** [Intel-bigdata/OAP#652]
### OAP 0.3.0 - Spark 2.1.0 API change -   BitSet (until commit 5b63c970bf8f6b)

_org.apache.spark.util.collection.BitSet_
**Before:** 
**After:**
Overload BitSet constructor
**Reason:**
Use an array to initialize BitSet member field.

**Comment by adrian-wang** [comment]
also add `toLongArray()` interface.

Since this util class is simple enough, considering fork this to OapBitSet, delete redundant methods from it.

**Comment by carsonwang** [comment]
```
@@ -32,6 +32,15 @@ class BitSet(numBits: Int) extends Serializable {
    */
   def capacity: Int = numWords * 64
 
+  def toLongArray(): Array[Long] = words
+
+  def this(from: Array[Long]) {
+    this(from.length << 6)
+    for(i <- from.indices) {
+      words(i) = from(i)
+    }
+  }
+
   /**
    * Clear all set bits.
    */
```

**Comment by carsonwang** [comment]
OAP is currently using a wrong version code which is from Spark 2.0.2 instead of 2.1.0

**Comment by carsonwang** [comment]
Todo: This change can actually be removed by implementing a BitSet in OAP.

**Comment by zhixingheyi-tian** [comment]
About spark2.3, changes are the same.

**Comment by LuciferYang** [comment]
Can we change to use `BitSet` in scala?

**Comment by adrian-wang** [comment]
`scala.collection.mutable.BitSet` and `scala.collection.immutable.BitSet` is slower than Spark's implementation because of safety/bound checking.

**Comment by LuciferYang** [comment]
Got it ~, @adrian-wang  Is there any suggestion to help us extend `org.apache.spark.util.collection.BitSet` instead of copy code?

**Comment by LuciferYang** [comment]
#982 do this work
