### ISSUE TITLE
OAP-Spark  Executor

### ISSUE THREAD

**Issue by Moonlit-Sailor** [Intel-bigdata/OAP#653]
### OAP 0.3.0 - Spark 2.1.0 API change -  Executor (until commit 5b63c970bf8f6b)

_org.apache.spark.executor.Executor_
**Before:**
**After:** Add `customInfoClassNameSeq` , `customManagerSeq.` Modify Heartbeat
**Reason:**
`customManagerSeq` handles corresponding heart beat message. Modify Heatbeat to add fiber info of each executor.

**Comment by gczsjdy** [comment]
Removed by #672
