### ISSUE TITLE
OAP-Spark  CustomManager

### ISSUE THREAD

**Issue by Moonlit-Sailor** [Intel-bigdata/OAP#654]
### OAP 0.3.0 - Spark 2.1.0 API change -   CustomManager  (until commit 5b63c970bf8f6b)

_org.apache.spark.executor.custom.CustomManager_
**Before:**
**After:**
Add CustomManager trait
**Reason:**
Add `status(conf: SparkConf): String` to get Fiber info from each executor

**Comment by gczsjdy** [comment]
Seems Spark doesn't contain this class? @Moonlit-Sailor
