### ISSUE TITLE
OAP-Spark HeartbeatReceiver

### ISSUE THREAD

**Issue by Moonlit-Sailor** [Intel-bigdata/OAP#658]
### OAP 0.3.0 - Spark 2.1.0 API change  HeartbeatReceiver (until commit 5b63c970bf8f6b)

_org.apache.spark.HeartbeatReceiver_
**Before:**
**After:**
Deal with fiber info of heart beat message in `receiveAndReply()` method
**Reason:**
Extract fiber info in heart beat and post it to listen bus.

**Comment by gczsjdy** [comment]
Removed by #672
