### ISSUE TITLE
OAP-Spark Heartbeat

### ISSUE THREAD

**Issue by Moonlit-Sailor** [Intel-bigdata/OAP#659]
### OAP 0.3.0 - Spark 2.1.0 API change -  Heartbeat (until commit 5b63c970bf8f6b)

_org.apache.spark.Heartbeat_
**Before:**
**After:**
Add `customizedInfo` field in `HeartBeat` class
**Reason:**
`customizedInfo` represents the fiber info of each executor.

**Comment by gczsjdy** [comment]
Resolved by #672
