### ISSUE TITLE
OAP-Spark SparkSqlAstBuilder

### ISSUE THREAD

**Issue by Moonlit-Sailor** [Intel-bigdata/OAP#662]
### OAP 0.3.0 - Spark 2.1.0 API change -  SparkSqlAstBuilder (until commit 5b63c970bf8f6b)

_org.apache.spark.sql.SparkSqlAstBuilder_
**Before:**
**After:**
Add `visitOapCreateIndex` , `visitOapDropIndex` ,  `visitIndexCols` , `visitIndexCol` , `visitIndexType` , `visitOapRefreshIndices` , `visitOapShowIndex` , `visitOapCheckIndex` , `visitOapEnableIndex` , `visitOapDisableIndex` methods
**Reason:**
Add these method to enable index relative DML.

**Comment by LuciferYang** [comment]
after #1005 no logger change this file
