### ISSUE TITLE
OAP-Spark DataSourceStrategy

### ISSUE THREAD

**Issue by Moonlit-Sailor** [Intel-bigdata/OAP#665]
### OAP 0.3.0 - Spark 2.1.0 API change -  DataSourceStrategy  (until commit 5b63c970bf8f6b)

_org.apache.spark.sql.execution.datasources.DataSourceStrategy_
**Before:**
**After:**
Add ‘expressions.Like’ process in `translateFilters()` method
**Reason:**
Enable spark to push down STRING_LIKE operator.

**Comment by carsonwang** [comment]
```
@@ -576,6 +576,9 @@ object DataSourceStrategy extends Strategy with Logging {
       case expressions.Contains(a: Attribute, Literal(v: UTF8String, StringType)) =>
         Some(sources.StringContains(a.name, v.toString))
 
+      case expressions.Like(a: Attribute, Literal(v: UTF8String, StringType)) =>
+        Some(sources.StringLike(a.name, v.toString))
+
       case _ => None
     }
   }
```

**Comment by zhixingheyi-tian** [comment]
About spark2.3, changes are the same.

**Comment by LuciferYang** [comment]
#933 remove import this class, close it.
