### ISSUE TITLE
ParquetFileFormat supports data cache

### ISSUE THREAD

**Issue by songzhan01** [Intel-bigdata/OAP#669]
Data cache is very important for improving performance.  OapFileFormat has supported but ParquetFileFormat has not yet.  However,  ParquetFileFormat is the main file format in Baidu OAP production and the large memory machine may be introduced in future.  The design is in the following google-doc: https://docs.google.com/document/d/1FLchKxcxuQXZm3v40Fw4L6i_LuV-OMxdZRbmwmBmqdQ/edit?usp=sharing

**Comment by LuciferYang** [comment]
already support
