### ISSUE TITLE
Messages are sent after RpcEnv is stopped

### ISSUE THREAD

**Issue by carsonwang** [Intel-bigdata/OAP#678]
A log of warnings like below in unit tests since the new RPC module.
22:21:31.557 WARN org.apache.spark.rpc.netty.NettyRpcEnv: RpcEnv already stopped.
22:21:33.557 WARN org.apache.spark.rpc.netty.NettyRpcEnv: RpcEnv already stopped.
22:21:35.557 WARN org.apache.spark.rpc.netty.NettyRpcEnv: RpcEnv already stopped.

**Comment by gczsjdy** [comment]
I'm investigating on this, seems it's due to in local mode(unit tests), the Heartbeat will be sent consistently, while the RpcEnv will stop due to unit test termination.

**Comment by carsonwang** [comment]
#690 properly shutdown the heartbeat thread. Even if there are still some warning message, they can be safely ignored. In the latest Spark code, the warning has been changed to debugging log.
