### ISSUE TITLE
Can `initialize` in FileFormat be removed?

### ISSUE THREAD

**Issue by gczsjdy** [Intel-bigdata/OAP#700]
`initialize` seems will only be called once after `xxFileFormat` is constructed.
It actually requires developers to manually call it, but it can be done automatically(in constructor or in a block in class).
Also, it looks too procedural.

**Comment by LuciferYang** [comment]
Perhaps we should keep this method, in #694 we found that fileformat instance for one table in one sparksession uses the same instance, in this proposition constructor is also called only once, we can't change status of fileformat instance if we remove `initialize` method.

**Comment by gczsjdy** [comment]
Thanks @LuciferYang .
From this point, seems Parquet's using index should take use of `OapFileFormat`, this is not very good...

**Comment by adrian-wang** [comment]
close this as duplicate to #647
