### ISSUE TITLE
Parquet cache has no effect when OAP index is disabled

### ISSUE THREAD

**Issue by zhangweilst** [Intel-bigdata/OAP#756]
Currently, we substitute the ParquetFileFormat to OapFileFormat when "hasAvailableIndex()" returns true, which means Oap index should be first enabled and there are indexes for the corresponding filter.
As a result, when Oap index is disabled, the substitution will not happen. Thus the reader used for parquet format file scan will be shipped from Spark, instead of the one defined in "ParquetDataFile" by OAP, which furthermore makes the parquet cache support ineffective.

**Comment by linhong-intel** [comment]
thanks @zhangweilst , good finding.
Let's have a discuss tomorrow

**Comment by LuciferYang** [comment]
#932 fix this
