### ISSUE TITLE
[BUG] BloomFilterStatisticsReader#analyse unexpected return SkipFile

### ISSUE THREAD

**Issue by LuciferYang** [Intel-bigdata/OAP#764]
If we query with `a in (1,2,3,4)` condition with `btree index` and `2, 3, 4` not exist in the data file of `a` column, then BloomFilterStatisticsReader#analyse may unexpected return `SKIP_INDEX` status because of we use `intervalArray.exists` api and one of `2,3,4` may not exist in `bfIndex`. 
The following case will trigger the problem:

test("bloom filter bug") {
    val data: Seq[(Int, String)] = (1 to 300).map { i => {
      if (i % 13 == 0) {
        (-1, "-1")
      } else {
        (i, s"this is test $i")
      }
    }
    }.filter(item => item._1 != -1)
    data.toDF("key", "value").createOrReplaceTempView("t")
    sql("insert overwrite table parquet_test select * from t")
    withSQLConf(OapConf.OAP_ENABLE_EXECUTOR_INDEX_SELECTION.key -> "true") {
      withIndex(TestIndex("parquet_test", "index1")) {
        sql("create oindex index1 on parquet_test (a)")
        checkAnswer(sql("SELECT * FROM parquet_test WHERE a in (1, 13, 26, 39, 52)"),
          Row(1, "this is test 1"):: Nil)
      }
    }
  }

Now, this case will return `empty result` not Row(1, "this is test 1")

**Comment by LuciferYang** [comment]
@linhong-intel @carsonwang

**Comment by LuciferYang** [comment]
== Results ==
!== Correct Answer - 1 ==   == Spark Answer - 0 ==
![1,this is test 1]         
	at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:495)

**Comment by LuciferYang** [comment]
In the past week, 10% of queries of bigsql service had been wrong due to this problem!!!

**Comment by linhong-intel** [comment]
fixed. sorry about this.
