### ISSUE TITLE
DAGScheduler.scala is using 2.0.2 version instead of 2.1.0

### ISSUE THREAD

**Issue by carsonwang** [Intel-bigdata/OAP#801]
DAGScheduler.scala is still using 2.0.2 version instead of 2.1.0. Need upgrade DAGScheduler.scala to 2.1.0.
Spark code: core/src/main/scala/org/apache/spark/scheduler/DAGScheduler.scala
OAP code: src/main/scala/org/apache/spark/scheduler/DAGScheduler.scala

**Comment by LuciferYang** [comment]
@carsonwang can we close this issuse?
