### ISSUE TITLE
OAP-Spark ParquetFilters.scala

### ISSUE THREAD

**Issue by carsonwang** [Intel-bigdata/OAP#802]
This only applies for Spark 2.1. For Spark 2.2 and later, this change is no longer necessary.

Spark code: sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetFilters.scala

OAP code:src/main/spark2.1/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetFilters.scala

**Comment by LuciferYang** [comment]
We can del this file
