### ISSUE TITLE
Compile error with profile spark-2.2

### ISSUE THREAD

**Issue by yunfan123** [Intel-bigdata/OAP#820]
[ERROR] /Users/yunfan/java/OAP/src/main/scala/org/apache/spark/sql/internal/oap/OapConf.scala:26: value SQLConfigBuilder is not a member of object org.apache.spark.sql.internal.SQLConf

**Comment by carsonwang** [comment]
@yunfan123 , the master branch doesn't fully support spark 2.2 yet, can you please apply this path https://github.com/Intel-bigdata/OAP/pull/813 before build for spark 2.2?

By they way, have you already been using OAP on spark 2.1 or just start to evaluate it?

**Comment by gczsjdy** [comment]
It should work now, you can try with master branch. @yunfan123
