### ISSUE TITLE
How to specific index path when create index?

### ISSUE THREAD

**Issue by yunfan123** [Intel-bigdata/OAP#821]
rt

**Comment by gczsjdy** [comment]
Do you mean to put index in a certain directory? If yes, you can configure it by `spark.sql.oap.index.directory`

**Comment by gczsjdy** [comment]
@JkSelf Could we also add some related info to README?

**Comment by JkSelf** [comment]
@gczsjdy  added the usage in readme.

**Comment by gczsjdy** [comment]
Resolved by #824
