### ISSUE TITLE
OapEnv is actually SparkSQLEnv

### ISSUE THREAD

**Issue by gczsjdy** [Intel-bigdata/OAP#833]
OapEnv actually copied from SparkSQLEnv, and some OAP-specific listener and UI class are added.
We'd better change it to SparkSQLEnv, therefore it's easier clearly recorded, i.e. for future version support.

Can be address after #813

**Comment by gczsjdy** [comment]
cc @adrian-wang

**Comment by adrian-wang** [comment]
So this is no longer an issue?

**Comment by gczsjdy** [comment]
@adrian-wang I will create a follow up PR later, guiding users to call `OapEnv.init` for spark-shell, spark-submit, etc.

**Comment by adrian-wang** [comment]
In 2.1 the creation is overriden in HiveThriftServer2.scala and SparkSQLCLIDriver.scala

**Comment by gczsjdy** [comment]
I know but these initializations are for spark-sql CLI and Thriftserver, in spark-shell users should manually do that

**Comment by gczsjdy** [comment]
This is no longer an issue:

> I figured out the reason... We didn't make it as SparkSQLEnv due to making it OapEnv grants us the ability to use OAP in Spark-shell(other than Spark-sql CLI or Thriftserver). Otherwise we should new a SparkSQLEnv in Spark-shell to enable the listener & UI tab, etc, but it's actually an OAP thing...

Followup patch #841
