### ISSUE TITLE
OAP-ColumnarBatchScan.scala

### ISSUE THREAD

**Issue by carsonwang** [Intel-bigdata/OAP#847]
This class is added in Spark2.2. In Spark 2.1, its code is included in DataSourceScanExec. Since we updated that part of code, we need add it. Some recoreds filtered by index so we mark them in filteredRows of ColumnarBatch, if batch.isFiltered(rowidx) return true, there is no need to push data to downstream.

Spark 2.2: sql/core/src/main/scala/org/apache/spark/sql/execution/ColumnarBatchScan.scala
OAP:src/main/spark2.2/scala/org/apache/spark/sql/execution/ColumnarBatchScan.scala

```
@@ -128,6 +128,7 @@ private[sql] trait ColumnarBatchScan extends CodegenSupport {
        |  int $localEnd = $numRows - $idx;
        |  for (int $localIdx = 0; $localIdx < $localEnd; $localIdx++) {
        |    int $rowidx = $idx + $localIdx;
+       |    if ($batch.isFiltered($rowidx)) continue;^M
        |    ${consume(ctx, columnsBatchInput).trim}
        |    $shouldStop
        |  }

```

**Comment by gczsjdy** [comment]
Thanks @carsonwang

**Comment by zhixingheyi-tian** [comment]
About spark2.3, changes are the same.

**Comment by LuciferYang** [comment]
#888 already remove this change.
