### ISSUE TITLE
OnHeapColumnVector.get takes much time due to reflection

### ISSUE THREAD

**Issue by gczsjdy** [Intel-bigdata/OAP#857]
> Use reflection get filed from OnHeapColumnVector slow 2~3 times than call accessor method.

Reported by Baidu developers @LuciferYang

**Comment by gczsjdy** [comment]
How did you test the discrepancy?
Like, by introducing some classes to OAP, and modify the fields related to `protected`(as the faster side)?

**Comment by LuciferYang** [comment]
- introduce `OnHeapColumnVector` and change one filed accessor modifier to protected or public, like for example `intData`

- use  benchmark framwork or write some code call OnHeapColumnVector.intData or `OnHeapCoumnVectorFiledAccessor.getFieldValue(vector, "intData")` many times(about One million times ) and record run time

- when code  optimization by JIT ，the performance gap will 2~3 times, discrepancy bigger before that

- reflection mode will construnct a `UnsafeObjectFieldAccessorImpl` instance, then  use unsafe api to get value  by fieldOffset in obj

**Comment by gczsjdy** [comment]
Thanks @LuciferYang 
Then what about the end to end performance gap? If it's relatively large, I think we should introduce the related classes to OAP even if maintainance cost will increase?

**Comment by LuciferYang** [comment]
@gczsjdy we will give a conclusion after we finish the performance evaluation of datacache with dram，now we use accessor not reflection, on the other hand, lee-lei will introduce the  `OnHeapColumnVector ` code in #843,  maybe we needn't to tangle this problem :)

**Comment by LuciferYang** [comment]
I rewrite the implementation in the actual performance test.....
