### ISSUE TITLE
Add support for Intel Optane DC persistent memory cache

### ISSUE THREAD

**Issue by ConeyLiu** [Intel-bigdata/OAP#864]
Intel Optane DC persistent memory provides another option for memory requirements. We need to support that.

Software requirements:

- [Memkind](https://github.com/memkind/memkind): The heap management of Intel Optane DC persistent memory

- CMake: compile and produce share library

**Comment by LuciferYang** [comment]
@ConeyLiu It looks like this issue has been completed ?

**Comment by ConeyLiu** [comment]
Hi @LuciferYang, this issue can be closed. There still need some test case or LRU cache implementation refactor which can be added later.

**Comment by LuciferYang** [comment]
Thank you for your reply @ConeyLiu , close this issue~
