### ISSUE TITLE
Need Support Spark 2.3.2

### ISSUE THREAD

**Issue by LuciferYang** [Intel-bigdata/OAP#900]
As we sync offline, in baidu we released the spark-2.3.2 version for user use, then our BigSQL serivce will upgrade to support this version, so we need OAP 0.5 version to support spark-2.3.2.

SubTasks：

- Import spark 2.3.2 source code (#950) 

- importCode from spark2.3.2 diff request (#951)

- Followup #951 Start to use spark-2.3.2 (#953)

**Comment by LuciferYang** [comment]
cc @jerrychenhf @xuanyuanking

**Comment by jcdauchy** [comment]
There is a discussion about multi-version support in OAP, so i guess when the technical solution is decided when can expect a spark 2.4 support ?

**Comment by LuciferYang** [comment]
Next major version may start support Spark-2.4.x.

**Comment by jcdauchy** [comment]
Thanks @LuciferYang is next major release is 0.5 or 0.6 ?

**Comment by LuciferYang** [comment]
@jcdauchy 0.6 ~
