### ISSUE TITLE
only support filter on single column?

### ISSUE THREAD

**Issue by WangGuangxin** [Intel-bigdata/OAP#903]
Hi，I do a simple test on OAP. I have a parquet table oap_test and create two index on column a and column b。 but the following sql **will not use index to accelerate.**
SELECT * FROM oap_test WHERE a = 1  or b = 819 

is this the right behavior?

**Comment by LuciferYang** [comment]
@WangGuangxin  can set `spark.sql.oap.indexer.max.use.size ` to use more than 1 index, default value is 1.

**Comment by Alex-Durandal** [comment]
Hello, I run a test on  a Parquet table, and created an index on column a. But the sql “ select count(*) from table1 where a<xxxx and a>xxx” didn’t faster than Parquet without index, and the input data was much more. Is it right? 
I used Spark 2.1.0.

**Comment by LuciferYang** [comment]
If `a=xxxx` cannot save io effectively, it's not suitable to use the index to speed up this sql, in this scenario there may more input data than spark-sql because we need read index data, and dataCache may speed up this sql.
