### ISSUE TITLE
One NoSuchMethodError happened when running OAP’DailyTest in Spark 2.1

### ISSUE THREAD

**Issue by zhixingheyi-tian** [Intel-bigdata/OAP#906]
Now，for the release of OAP 0.5，OAP’DailyTest is running every day.One NoSuchMethodError happened when running OAP’DailyTest in Spark 2.1

```
java.lang.NoSuchMethodError: org.apache.parquet.hadoop.ParquetFileReader.<init>(Lorg/apache/hadoop/conf/Configuration;Lorg/apache/hadoop/fs/Path;Lorg/apache/parquet/hadoop/metadata/ParquetMetadata;)V
```
Same as issue #904. After the rollback test. The problem still points to #880
@LuciferYang 

Thanks

**Comment by LuciferYang** [comment]
for spark 2.1, we need replace parquet-1.8.1 jars to  parquet 1.8.2  jars.

**Comment by zhixingheyi-tian** [comment]
@LuciferYang  
But 
in #880 , about parquet version, there is no version modification
