### ISSUE TITLE
Discuss the best way to support multi-version spark

### ISSUE THREAD

**Issue by LuciferYang** [Intel-bigdata/OAP#907]
Now Oap use 3 profile include spark-2.1, spark-2.3, spark-2.3 and default is spark-2.1 to support multi spark version, there may be some problems in our development as following:

1. we use `build-helper-maven-plugin` to manage source code, but maven think the code under the `src` directory is source code, we have to use `maven-compiler-plugin`  to exclude some dir like 
```
      <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <configuration>
              <excludes>
                <exclude>src/main/spark2.1</exclude>
                <exclude>src/main/spark2.3</exclude>
                <exclude>src/main/spark2.3.2</exclude>
                <exclude>src/test/spark2.1</exclude>
                <exclude>src/test/spark2.3</exclude>
                <exclude>src/test/spark2.3.2</exclude>
              </excludes>
            </configuration>
        </plugin>
``` 
we have to add more `<exclude>` tags in current model if we support for more spark versions, It's very hard to management.

2. Implementing a new feature we have to support all versions at the same time. For example #825, I support spark 2.1 & spark 2.2 and give a pr, in this time we begin to support spark-2.3 , then I have to support spark 2.3 immediately.  And for #909, there are some optimization of parquet data cache，but now it only support spark-2.1, we don't have support requirements for spark 2.2 and spark 2.3 immediately, but we have to implement them if we want to merge it to master.

3. We use `<classifier>` tag to distinguish which spark version oap dep, but it has a compiler conflict with the `maven-shade-plugin`, so we can't compile a fat jar with `maven-shade-plugin`.

4. Intellij think source code dir is `src/main/spark2.1` ,`src/main/spark2.2` or `src/main/spark2.3`, we need to manual configuration it let ide know source code dir are `src/main/spark2.x/java` and `src/main/spark2.x/scala`, it's unfriendly to developers.

**Comment by LuciferYang** [comment]
cc @jerrychenhf @xuanyuanking @songzhan01

**Comment by LuciferYang** [comment]
@jerrychenhf @xuanyuanking My suggestion is to use different branchs to support different versions of spark, and each branch only supports the latest major version of spark, like `branch-spark-2.3` only support `spark-2.3.2`

**Comment by xuanyuanking** [comment]
I prefer to add the multi-version support by branch, also as the Apache Spark manage the versions. The master can be used for daily work and each branch keep align with Spark.
```
like branch-spark-2.3 only support spark-2.3.2
```
If we need support multi sub-version in same branch, this can be done by tags, just has one drawback that new features couldn't conveniently back port to old version.

**Comment by zhixingheyi-tian** [comment]
@LuciferYang 

Problem 1:
Multiple profiles do cause trouble.
But the <exclude> configuration item seems to be removed. Compilation is also unaffected.

Problem 2:
This is because of the previous plan, OAP-0.5 should support spark2.1,spark2.2, and spark2.3 simultaneously. The development of new features requires support for three versions of spark.

Problem 3:
There is already a better solution to this conflict. #915

Problem 4:
With the following configuration items, Intellij can identify source code dir.
```
<activation>
        <activeByDefault>true</activeByDefault>
      </activation>
```

**Comment by zhixingheyi-tian** [comment]
@xuanyuanking  @LuciferYang 
Your idea is a bit like the iteration of spark.
But in this case, OAP will have a lot of tags, which needs to be discussed carefully.

**Comment by zhixingheyi-tian** [comment]
From the developer's perspective, the current multi-profile approach seems very unfriendly. Originally planned to start with spark2.4, remove this multi-profile.

The most critical issue now is how the OAP version is iteratively upgraded, which is strictly consistent with spark, or has independent releasing rules.

Thanks.

**Comment by LuciferYang** [comment]
```
Problem 4:
With the following configuration items, Intellij can identify source code dir.

<activation>
        <activeByDefault>true</activeByDefault>
      </activation>
```
are u sure ? in pom.xml, spark-2.1 profile is already config `<activeByDefault>true</activeByDefault>`, when I choice spark-2.1 profile in `Maven Projects Tabe`, then from `Modules Tab `, source are `src/main/spark-2.1` ,`src/main/spark-2.2`,`src/main/spark-2.3`, but we need `src/main/spark-2.1/java` and `src/main/spark-2.1/scala`

**Comment by LuciferYang** [comment]
```
@xuanyuanking @LuciferYang
Your idea is a bit like the iteration of spark.
But in this case, OAP will have a lot of tags, which needs to be discussed carefully.
```
You mean we need to add more profile like spark-2.3.1,spark-2.3.2,spark-2.3.*?

**Comment by LuciferYang** [comment]
```
Problem 2:
This is because of the previous plan, OAP-0.5 should support spark2.1, spark2.2, and spark2.3 simultaneously. The development of new features requires support for three versions of spark.
```

Maybe the difference is that we are developers and users at the same time, from the developer's point of view, I agree with this view, but as a user, only one specific version support specific features is enough to us.So I prefer to first support a certain feature in one spark version, and support other spark versions with this feature later, rather than one-time support for all spark versions.

**Comment by zhixingheyi-tian** [comment]
@LuciferYang 

 about   item <activeByDefault>true</activeByDefault>. This method  doesn't  hide other source directories. 
Only works when the code jumps.

**Comment by zhixingheyi-tian** [comment]
```
Maybe the difference is that we are developers and users at the same time, from the developer's point of view, I agree with this view, but as a user, only one specific version support specific features is enough to us.So I prefer to first support a certain feature for one spark version, and support other spark versions with this feature later, rather than one-time support for all spark versions.
```
This method is good as long as it can solve the OAP version release problem.

**Comment by LuciferYang** [comment]
Now we migrate a feature from `profile spark-version1` to `profile spark-version2`  need merge code manually, Is there a better way? If use branch mode, we can use `cherry-pick` to migrate a feature  from `oap support spark-version1` to `oap support  spark-version2`.

**Comment by zhixingheyi-tian** [comment]
@LuciferYang 
There are many differences between big versions of Spark. Cherry-pick may not solve the problem.

**Comment by LuciferYang** [comment]
@zhixingheyi-tian 
can't solve all problems does not mean that problems can not be solved, as oap \parquet\orc & data cache part,we can migrate a feature by cherry-pick and modification

**Comment by zhixingheyi-tian** [comment]
Hi,all

Here are two solutions, let's discuss them together.
First option, pull the 0.5 branch separately for the codes of OAP master branch. In the future, the master of OAP only supports the latest version of spark we need.
Second option, the current master codes is divided into three branches, each branch supports a big version of spark.In this situation, pay attention to the OAP's version of each branch.

I personally prefer the first.

Thanks
