### ISSUE TITLE
Code style error in profile source code dir

### ISSUE THREAD

**Issue by LuciferYang** [Intel-bigdata/OAP#910]
May check-style plugin not check java & scala source code in profile dir , like `src/main/spark2.1/scala/org/apache/spark/status/api/v1/ApiRootResource.scala`, there are many unused import statement, but there is no compile failures.

**Comment by adrian-wang** [comment]
Unused import will not be checked, I think...

**Comment by LuciferYang** [comment]
Long time no see ~ Teacher  Wang ~
