### ISSUE TITLE
Misjudged by MinMaxStatisticsReader & PartByValueStatisticsReader about like query.

### ISSUE THREAD

**Issue by LuciferYang** [Intel-bigdata/OAP#978]
Test case as following will checkAnswer failed when enable `OAP_ENABLE_EXECUTOR_INDEX_SELECTION` and `OAP_EXECUTOR_INDEX_SELECTION_STATISTICS_POLICY `:
```
val data: Seq[(Int, String)] =
      scala.util.Random.shuffle(30 to 90).map(i => (i, s"this$i is test"))
    data.toDF("key", "value").createOrReplaceTempView("t")
    sql("insert overwrite table oap_test_1 select * from t")
    withIndex(TestIndex("oap_test_1", "index1")) {
      sql("create oindex index1 on oap_test_1 (b) using btree")
      val ret = sql("SELECT a FROM oap_test_1 WHERE b like 'this3%'")
      checkAnswer(ret, Row(30) :: Row(31) :: Row(32) :: Row(33) :: Row(34) :: Row(35) :: Row(36)
        :: Row(37) :: Row(38) :: Row(39) :: Nil)
    }
```

The root cause is MinMaxStatisticsReader may do misjudged in `startWith` case

**Comment by LuciferYang** [comment]
Actually, PartByValueStatisticsReader will do misjudged when this query also.I don't know is there any other bug about startwith like query.

**Comment by LuciferYang** [comment]
@zhixingheyi-tian @jerrychenhf  @LinhongLiu maybe we should optimize this feature as #837 said.

**Comment by LuciferYang** [comment]
sorry `OAP_ENABLE_EXECUTOR_INDEX_SELECTION` and `OAP_EXECUTOR_INDEX_SELECTION_STATISTICS_POLICY`

**Comment by zhixingheyi-tian** [comment]
@LuciferYang 
When using PrefixMatch query ,users can disable OAP_EXECUTOR_INDEX_SELECTION_STATISTICS_POLICY .
Is this simpler?

**Comment by LuciferYang** [comment]
done
