### ISSUE TITLE
Use SparkSessionExtensions instead of Hard coding 

### ISSUE THREAD

**Issue by LuciferYang** [Intel-bigdata/OAP#988]
SPARK-18127(after and include spark-2.2.0 ) provided a extension to use custom `Rule`,`Strategy` or `Parser` and a new config `spark.sql.extensions` to appoint extension class:

```
 val SPARK_SESSION_EXTENSIONS = buildStaticConf("spark.sql.extensions")
    .doc("Name of the class used to configure Spark Session extensions. The class should " +
      "implement Function1[SparkSessionExtension, Unit], and must have a no-args constructor.")
    .stringConf
    .createOptional
```
we can try to use `SparkSessionExtensions` to extension our `Strategy` and `Parser`.

**Comment by LuciferYang** [comment]
I have do a simple experiment to verify the feasibility:

-  Add `OapSparkSqlAstBuilder` extends `SparkSqlAstBuilder` and add oap method to `OapSparkSqlAstBuilder`

- Add `OapSparkSqlParser` refer to `SparkSqlParser`

- Add `OapExtensions`  as following:
```
class OapExtensions extends (SparkSessionExtensions => Unit) {
  override def apply(extensions: SparkSessionExtensions): Unit = {
    extensions.injectParser((_, _) => new OapSparkSqlParser(new SQLConf))
  }
}
```

- Delete `SparkSqlParser` from oap 

Do a test as following:

create SparkSession:

```
val session = SparkSession.builder()
      .master("local[2]")
      .appName("test-sql-context")
      .config("spark.memory.offHeap.size", "100m")
      .config("spark.sql.testkey", "true")
      .withExtensions(new OapExtensions)
      .getOrCreate()
```

then write  query suite use this session passed:

```
val path = Utils.createTempDir().getAbsolutePath
      session.sql(s"""CREATE TEMPORARY VIEW parquet_test (a INT, b STRING)
                     | USING parquet
                     | OPTIONS (path '$path')""".stripMargin)


      val data: Seq[(Int, String)] = (1 to 300).map { i => (i, s"this is test $i") }
      session.createDataFrame(data)
        .toDF("key", "value").createOrReplaceTempView("t")

      session.sql("insert overwrite table parquet_test select * from t")
      session.sql("create oindex index1 on parquet_test (a)")
      val rows = session.sql("select a from parquet_test where a = 1").collect()
      assert(rows.length == 1)
      assert(rows.head.getInt(0) == 1)
      session.sql("drop oindex index1 on parquet_test")
```

**Comment by LuciferYang** [comment]
There's some work left：

- Add a new Test Framework for Oap , now we  use `SharedSQLContext` system and `SharedSQLContext`  init `TestSparkSession` use `SparkSession(sc)` method, rather than `SparkSession.builder` method,  but `SparkSession(sc)`  api can't inject Extensions.

- Write a `OapFileSourceStrategy` inject to SparkSessionExtensions then we can avoid introduce `FileSourceStrategy` from spark source.

**Comment by LuciferYang** [comment]
#995 to remove  `FileSourceStrategy `

**Comment by gczsjdy** [comment]
Good. : )

**Comment by LuciferYang** [comment]
#995 #1001 #1005 do this work, close this.
